import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, variables?: Record<string, string>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Comprehensive translation dictionary
const translations = {
  en: {
    // Common
    'app.name': 'DeliveryMatch',
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.close': 'Close',
    'common.submit': 'Submit',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.back': 'Back',
    'common.continue': 'Continue',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.view': 'View',
    'common.upload': 'Upload',
    'common.download': 'Download',
    'common.print': 'Print',
    'common.share': 'Share',
    'common.copy': 'Copy',
    'common.paste': 'Paste',
    'common.cut': 'Cut',
    'common.undo': 'Undo',
    'common.redo': 'Redo',
    'common.select_all': 'Select All',
    'common.clear': 'Clear',
    'common.reset': 'Reset',
    'common.refresh': 'Refresh',
    'common.update': 'Update',
    'common.create': 'Create',
    'common.new': 'New',
    'common.open': 'Open',
    'common.start': 'Start',
    'common.stop': 'Stop',
    'common.pause': 'Pause',
    'common.resume': 'Resume',
    'common.finish': 'Finish',
    'common.complete': 'Complete',
    'common.pending': 'Pending',
    'common.approved': 'Approved',
    'common.rejected': 'Rejected',
    'common.expired': 'Expired',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.enabled': 'Enabled',
    'common.disabled': 'Disabled',
    'common.available': 'Available',
    'common.unavailable': 'Unavailable',
    'common.online': 'Online',
    'common.offline': 'Offline',
    'common.connected': 'Connected',
    'common.disconnected': 'Disconnected',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.warning': 'Warning',
    'common.info': 'Info',
    'common.help': 'Help',
    'common.support': 'Support',
    'common.contact': 'Contact',
    'common.about': 'About',
    'common.privacy': 'Privacy',
    'common.terms': 'Terms',
    'common.settings': 'Settings',
    'common.preferences': 'Preferences',
    'common.profile': 'Profile',
    'common.account': 'Account',
    'common.dashboard': 'Dashboard',
    'common.home': 'Home',
    'common.logout': 'Logout',
    'common.login': 'Login',
    'common.signup': 'Sign Up',
    'common.signin': 'Sign In',
    'common.email': 'Email',
    'common.password': 'Password',
    'common.username': 'Username',
    'common.name': 'Name',
    'common.first_name': 'First Name',
    'common.last_name': 'Last Name',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.city': 'City',
    'common.state': 'State',
    'common.country': 'Country',
    'common.zip_code': 'ZIP Code',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.today': 'Today',
    'common.yesterday': 'Yesterday',
    'common.tomorrow': 'Tomorrow',
    'common.week': 'Week',
    'common.month': 'Month',
    'common.year': 'Year',
    'common.hour': 'Hour',
    'common.minute': 'Minute',
    'common.second': 'Second',
    'common.price': 'Price',
    'common.cost': 'Cost',
    'common.total': 'Total',
    'common.subtotal': 'Subtotal',
    'common.tax': 'Tax',
    'common.discount': 'Discount',
    'common.fee': 'Fee',
    'common.amount': 'Amount',
    'common.quantity': 'Quantity',
    'common.weight': 'Weight',
    'common.size': 'Size',
    'common.dimension': 'Dimension',
    'common.length': 'Length',
    'common.width': 'Width',
    'common.height': 'Height',
    'common.volume': 'Volume',
    'common.description': 'Description',
    'common.note': 'Note',
    'common.comment': 'Comment',
    'common.message': 'Message',
    'common.notification': 'Notification',
    'common.alert': 'Alert',
    'common.reminder': 'Reminder',
    'common.language': 'Language',

    // Header
    'header.driver': 'Driver',
    'header.customer': 'Customer',

    // Landing Page
    'landing.title': 'Smart Delivery Platform',
    'landing.subtitle': 'Connect with verified drivers for efficient goods delivery. From single packages to bulk shipments, our AI-powered platform optimizes routes and reduces costs.',
    'landing.get_started': 'Get Started',
    'landing.ship_now': 'Ship Now',
    'landing.drive_earn': 'Drive & Earn',
    'landing.stats.drivers': 'Active Drivers',
    'landing.stats.deliveries': 'Deliveries Completed',
    'landing.stats.cities': 'Cities Covered',
    'landing.stats.rating': 'Average Rating',
    'landing.features.title': 'Why Choose DeliveryMatch?',
    'landing.features.subtitle': 'Built for efficiency, designed for scale. Our platform revolutionizes how goods move from point A to point B.',
    'landing.features.smart_matching.title': 'Smart Matching',
    'landing.features.smart_matching.desc': 'AI-powered algorithm matches orders with the most suitable drivers based on capacity, location, and route optimization.',
    'landing.features.bulk_orders.title': 'Bulk Orders',
    'landing.features.bulk_orders.desc': 'Upload multiple deliveries via Excel and get optimized route planning that saves time and fuel costs.',
    'landing.features.real_time_tracking.title': 'Real-time Tracking',
    'landing.features.real_time_tracking.desc': 'Track your deliveries in real-time with live GPS updates and instant notifications.',
    'landing.features.secure_reliable.title': 'Secure & Reliable',
    'landing.features.secure_reliable.desc': 'Verified drivers, secure payments, and comprehensive insurance coverage for peace of mind.',
    'landing.how_it_works.title': 'How It Works',
    'landing.how_it_works.subtitle': 'Simple steps to get your delivery moving',
    'landing.how_it_works.customers': 'For Customers',
    'landing.how_it_works.drivers': 'For Drivers',
    'landing.how_it_works.customer_step1': 'Create Request',
    'landing.how_it_works.customer_step1_desc': 'Enter pickup & delivery details',
    'landing.how_it_works.customer_step2': 'Get Matched',
    'landing.how_it_works.customer_step2_desc': 'AI finds the best driver for you',
    'landing.how_it_works.customer_step3': 'Track & Receive',
    'landing.how_it_works.customer_step3_desc': 'Real-time updates until delivery',
    'landing.how_it_works.driver_step1': 'Sign Up & Verify',
    'landing.how_it_works.driver_step1_desc': 'Upload documents & vehicle info',
    'landing.how_it_works.driver_step2': 'Get Orders',
    'landing.how_it_works.driver_step2_desc': 'Accept nearby delivery requests',
    'landing.how_it_works.driver_step3': 'Earn Money',
    'landing.how_it_works.driver_step3_desc': 'Complete deliveries & get paid',
    'landing.cta.title': 'Ready to Get Started?',
    'landing.cta.subtitle': 'Join thousands of customers and drivers who trust DeliveryMatch for their delivery needs.',
    'landing.cta.button': 'Start Your First Delivery',
    'landing.footer.subtitle': 'Connecting drivers and customers for efficient goods delivery.',

    // Auth Page
    'auth.title': 'DeliveryMatch',
    'auth.login.welcome': 'Welcome back!',
    'auth.signup.welcome': 'Create your account',
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.account_type': 'I want to:',
    'auth.customer_option': 'Ship goods and packages',
    'auth.driver_option': 'Drive and earn money',
    'auth.confirm_password': 'Confirm Password',
    'auth.agree_terms': 'I agree to the Terms of Service and Privacy Policy',
    'auth.forgot_password': 'Forgot your password?',
    'auth.no_account': "Don't have an account?",
    'auth.have_account': 'Already have an account?',
    'auth.demo_access': 'Quick Demo Access:',
    'auth.demo_customer': 'Demo Customer',
    'auth.demo_driver': 'Demo Driver',

    // Driver Dashboard
    'driver.dashboard.title': 'Driver Dashboard',
    'driver.dashboard.welcome': 'Welcome back, Driver!',
    'driver.dashboard.status': 'Status',
    'driver.dashboard.available': 'Available',
    'driver.dashboard.busy': 'Busy',
    'driver.dashboard.go_online': 'Go Online',
    'driver.dashboard.go_offline': 'Go Offline',
    'driver.dashboard.today_earnings': 'Today\'s Earnings',
    'driver.dashboard.active_orders': 'Active Orders',
    'driver.dashboard.completion_rate': 'Completion Rate',
    'driver.dashboard.rating': 'Your Rating',
    'driver.dashboard.available_orders': 'Available Orders',
    'driver.dashboard.no_orders': 'No available orders right now',
    'driver.dashboard.check_back': 'Check back in a few minutes for new delivery requests.',
    'driver.dashboard.accept_order': 'Accept Order',
    'driver.dashboard.pickup': 'Pickup',
    'driver.dashboard.delivery': 'Delivery',
    'driver.dashboard.earnings': 'Earnings',
    'driver.dashboard.distance': 'Distance',
    'driver.dashboard.quick_stats': 'Quick Stats',
    'driver.dashboard.this_week': 'This Week',
    'driver.dashboard.deliveries': 'Deliveries',
    'driver.dashboard.hours_online': 'Hours Online',

    // Navigation Tabs
    'nav.dashboard': 'Dashboard',
    'nav.orders': 'Active Orders',
    'nav.earnings': 'Earnings',
    'nav.notifications': 'Notifications',
    'nav.profile': 'Profile',
    'nav.booking': 'New Booking',
    'nav.bulk': 'Bulk Upload',
    'nav.tracking': 'Track Orders',
    'nav.matching': 'Find Drivers',

    // Notifications
    'notifications.title': 'Notifications',
    'notifications.unread': 'unread notifications',
    'notifications.all_caught_up': 'All caught up!',
    'notifications.mark_all_read': 'Mark All Read',
    'notifications.all': 'All',
    'notifications.unread_tab': 'Unread',
    'notifications.orders': 'Orders',
    'notifications.payments': 'Payments',
    'notifications.system': 'System',
    'notifications.settings': 'Settings',
    'notifications.preferences': 'Notification Preferences',
    'notifications.preferences_desc': 'Choose what notifications you want to receive',
    'notifications.types': 'Notification Types',
    'notifications.order_updates': 'Order Updates',
    'notifications.order_updates_desc': 'New orders, status changes, completions',
    'notifications.payment_notifications': 'Payment Notifications',
    'notifications.payment_notifications_desc': 'Payment confirmations, earnings updates',
    'notifications.system_updates': 'System Updates',
    'notifications.system_updates_desc': 'App updates, maintenance notifications',
    'notifications.promotions': 'Promotions & Tips',
    'notifications.promotions_desc': 'Special offers, driving tips, platform updates',
    'notifications.delivery_methods': 'Delivery Methods',
    'notifications.email_notifications': 'Email Notifications',
    'notifications.email_notifications_desc': 'Receive notifications via email',
    'notifications.sms_notifications': 'SMS Notifications',
    'notifications.sms_notifications_desc': 'Receive notifications via text message',
    'notifications.push_notifications': 'Push Notifications',
    'notifications.push_notifications_desc': 'Receive notifications in the app',
    'notifications.no_notifications': 'No notifications',
    'notifications.no_unread': 'All caught up! No unread notifications.',
    'notifications.no_category': 'No notifications in this category.',

    // Driver Profile
    'driver.profile.title': 'Driver Profile',
    'driver.profile.approved_drive': 'Approved to Drive',
    'driver.profile.cannot_drive': 'Cannot Drive',
    'driver.profile.completion': 'Profile Completion',
    'driver.profile.personal_info': 'Personal Information',
    'driver.profile.vehicle_info': 'Vehicle Information',
    'driver.profile.documents': 'Documents',
    'driver.profile.statistics': 'Statistics',
    'driver.profile.edit_profile': 'Edit Profile',
    'driver.profile.save_changes': 'Save Changes',
    'driver.profile.edit_vehicle': 'Edit Vehicle',
    'driver.profile.date_birth': 'Date of Birth',
    'driver.profile.member_since': 'Member Since',
    'driver.profile.vehicle_type': 'Vehicle Type',
    'driver.profile.license_plate': 'License Plate',
    'driver.profile.make': 'Make',
    'driver.profile.model': 'Model',
    'driver.profile.year': 'Year',
    'driver.profile.color': 'Color',
    'driver.profile.max_weight': 'Max Weight (kg)',
    'driver.profile.max_volume': 'Max Volume (m³)',
    'driver.profile.update_photo': 'Update Photo',
    'driver.profile.required_documents': 'Required Documents',
    'driver.profile.documents_desc': 'Keep your documents up to date to continue driving',
    'driver.profile.action_required': 'Action Required',
    'driver.profile.document_issues': 'You cannot accept orders until all document issues are resolved. Please upload or renew expired documents.',
    'driver.profile.driver_license': 'Driver License',
    'driver.profile.auto_insurance': 'Auto Insurance',
    'driver.profile.vehicle_registration': 'Vehicle Registration',
    'driver.profile.vehicle_inspection': 'Vehicle Inspection',
    'driver.profile.uploaded': 'Uploaded',
    'driver.profile.expires': 'Expires',
    'driver.profile.rejected': 'Rejected',
    'driver.profile.reupload': 'Re-upload',
    'driver.profile.upload_document': 'Upload Document',
    'driver.profile.upload_desc': 'Please upload a new {document} document. Make sure it\'s clear and not expired.',
    'driver.profile.stats.total_deliveries': 'Total Deliveries',
    'driver.profile.stats.average_rating': 'Average Rating',
    'driver.profile.stats.total_earnings': 'Total Earnings',
    'driver.profile.stats.completion_rate': 'Completion Rate',
    'driver.profile.verification': 'Verification Status',
    'driver.profile.background_check': 'Background Check',
    'driver.profile.driving_authorization': 'Driving Authorization',
    'driver.profile.authorized': 'Authorized',
    'driver.profile.suspended': 'Suspended',

    // Customer Profile
    'customer.profile.title': 'Customer Profile',
    'customer.profile.business_account': 'Business Account',
    'customer.profile.member_since': 'Member since',
    'customer.profile.personal': 'Personal',
    'customer.profile.addresses': 'Addresses',
    'customer.profile.payment': 'Payment',
    'customer.profile.preferences': 'Preferences',
    'customer.profile.statistics': 'Statistics',
    'customer.profile.personal_info': 'Personal Information',
    'customer.profile.business_info': 'Business Information',
    'customer.profile.business_name': 'Business Name',
    'customer.profile.business_type': 'Business Type',
    'customer.profile.business_address': 'Business Address',
    'customer.profile.business_phone': 'Business Phone',
    'customer.profile.tax_id': 'Tax ID',
    'customer.profile.saved_addresses': 'Saved Addresses',
    'customer.profile.add_address': 'Add Address',
    'customer.profile.default': 'Default',
    'customer.profile.set_default': 'Set Default',
    'customer.profile.delete_address': 'Delete Address',
    'customer.profile.delete_address_confirm': 'Are you sure you want to delete this address? This action cannot be undone.',
    'customer.profile.payment_methods': 'Payment Methods',
    'customer.profile.add_payment_method': 'Add Payment Method',
    'customer.profile.remove_payment_method': 'Remove Payment Method',
    'customer.profile.remove_payment_confirm': 'Are you sure you want to remove this payment method? This action cannot be undone.',
    'customer.profile.notification_prefs': 'Notification Preferences',
    'customer.profile.privacy_prefs': 'Privacy Preferences',
    'customer.profile.share_location': 'Share Location Data',
    'customer.profile.share_location_desc': 'Help improve route optimization',
    'customer.profile.share_analytics': 'Share Usage Analytics',
    'customer.profile.share_analytics_desc': 'Help improve the platform',
    'customer.profile.marketing_emails': 'Marketing Emails',
    'customer.profile.marketing_emails_desc': 'Promotional offers and tips',
    'customer.profile.account_stats': 'Account Statistics',
    'customer.profile.total_orders': 'Total Orders',
    'customer.profile.total_spent': 'Total Spent',
    'customer.profile.average_rating': 'Average Rating',
    'customer.profile.days_active': 'Days Active',
    'customer.profile.account_benefits': 'Account Benefits',
    'customer.profile.free_delivery': 'Free Delivery Credits',
    'customer.profile.loyalty_points': 'Loyalty Points',
    'customer.profile.bulk_discount': 'Bulk Discount Rate',

    // Earnings
    'earnings.title': 'Earnings & Payments',
    'earnings.subtitle': 'Manage your earnings and payment methods',
    'earnings.withdraw_funds': 'Withdraw Funds',
    'earnings.available_balance': 'Available Balance',
    'earnings.pending_payments': 'Pending Payments',
    'earnings.this_week': 'This Week',
    'earnings.total_earned': 'Total Earned',
    'earnings.overview': 'Overview',
    'earnings.transactions': 'Transaction History',
    'earnings.payment_methods': 'Payment Methods',
    'earnings.how_paid': 'How You Get Paid',
    'earnings.complete_delivery': 'Complete Delivery',
    'earnings.complete_delivery_desc': 'Customer confirms delivery and payment is processed',
    'earnings.payment_options': 'Payment Options',
    'earnings.cash_immediate': 'Cash: Keep immediately (report in app)',
    'earnings.card_digital': 'Card/Digital: Added to your balance',
    'earnings.automatic_payouts': 'Automatic Payouts',
    'earnings.daily_transfers': 'Daily automatic transfers to your bank',
    'earnings.weekly_transfers': 'Weekly automatic transfers to your bank',
    'earnings.instant_transfers': 'Instant transfers available',
    'earnings.next_payout': 'Next Payout',
    'earnings.recent_activity': 'Recent Activity',
    'earnings.withdraw_title': 'Withdraw Earnings',
    'earnings.payment_method': 'Payment Method',
    'earnings.select_payment_method': 'Select payment method',
    'earnings.minimum_withdrawal': 'Minimum withdrawal',
    'earnings.processing_time': 'Processing time: 1-3 business days',
    'earnings.no_fees': 'No withdrawal fees for bank transfers',
    'earnings.process_withdrawal': 'Process Withdrawal',
    'earnings.add_payment_method': 'Add Payment Method',
    'earnings.cash_payments': 'Cash Payments',
    'earnings.cash_instructions': 'Cash Payment Instructions',
    'earnings.cash_collect': 'Collect cash payment directly from customers',
    'earnings.cash_receipt': 'Always provide a receipt if requested',
    'earnings.cash_report': 'Report cash earnings in the app immediately after delivery',
    'earnings.cash_safe': 'Keep cash safe and deposit regularly',
    'earnings.cash_no_withdraw': 'Cash earnings are added to your total but don\'t require withdrawal',
    'earnings.add_payment_title': 'Add Payment Method',
    'earnings.add_payment_desc': 'Add a new way to receive your earnings',
    'earnings.payment_type': 'Payment Type',
    'earnings.bank_account': 'Bank Account',
    'earnings.digital_wallet': 'Digital Wallet (PayPal, etc.)',
    'earnings.account_name': 'Account Name',
    'earnings.account_details': 'Account Details',

    // Units and measurements
    'units.kg': 'kg',
    'units.m3': 'm³',
    'units.km': 'km',
    'units.minutes': 'minutes',
    'units.hours': 'hours',
    'units.days': 'days',

    // Status and states
    'status.pending': 'Pending',
    'status.approved': 'Approved',
    'status.rejected': 'Rejected',
    'status.expired': 'Expired',
    'status.completed': 'Completed',
    'status.processing': 'Processing',
    'status.failed': 'Failed',
    'status.active': 'Active',
    'status.inactive': 'Inactive',

    // CUSTOMER BOOKING
    'customer.booking.title': 'Delivery Price Calculator',
    'customer.booking.subtitle': 'Get instant price estimates for your delivery',
    'customer.booking.price_estimate': 'Fill in all fields to see price estimate',
    'customer.booking.pickup_address': 'Pickup Address',
    'customer.booking.delivery_address': 'Delivery Address',
    'customer.booking.item_category': 'Item Category',
    'customer.booking.weight': 'Weight (kg)',
    'customer.booking.volume': 'Volume (m³)',
    'customer.booking.urgency': 'Delivery Urgency',
    'customer.booking.special_requirements': 'Special Requirements',
    'customer.booking.fragile': 'Fragile items',
    'customer.booking.refrigerated': 'Refrigerated',
    'customer.booking.oversized': 'Oversized',
    'customer.booking.hazardous': 'Hazardous',
    'customer.booking.book_delivery': 'Book Delivery for ${amount}',
    'customer.booking.calculating': 'Calculating...',

    // BULK BOOKING
    'customer.bulk.title': 'Bulk Order Upload',
    'customer.bulk.subtitle': 'Upload multiple orders at once using an Excel file',
    'customer.bulk.download_template': 'Download Template',
    'customer.bulk.choose_file': 'Choose File',
    'customer.bulk.upload_success': 'Uploaded: ${filename}',
    'customer.bulk.processing': 'Processing...',
    'customer.bulk.review_orders': 'Review Orders (${count})',
    'customer.bulk.optimize_routes': 'Optimize Routes',
    'customer.bulk.confirm_booking': 'Confirm Booking',
    // 'customer.bulk.orders_placed': 'Orders Placed', // Removed duplicate key
    'customer.bulk.vehicles_assigned': 'Vehicles Assigned',
    'customer.bulk.total_cost': 'Total Cost',
    'customer.bulk.fuel_savings': 'Fuel Savings',

    // ORDER TRACKING
    'customer.tracking.my_orders': 'My Orders',
    'customer.tracking.your_orders': 'Your Orders',
    'customer.tracking.progress': 'Progress',
    'customer.tracking.eta': 'ETA: ${time}',
    'customer.tracking.driver_info': 'Driver Information',
    'customer.tracking.pickup_address': 'Pickup Address',
    'customer.tracking.delivery_address': 'Delivery Address',
    'customer.tracking.order_timeline': 'Order Timeline',
    'customer.tracking.mark_delivered': 'Mark as Delivered',
    'customer.tracking.rate_driver': 'Rate Driver',

    // MATCHING ENGINE
    'customer.matching.title': 'Driver Matching Engine',
    'customer.matching.subtitle': 'Find the best drivers based on your requirements',
    'customer.matching.find_drivers': 'Find Drivers',
    'customer.matching.location': 'Pickup Location',
    'customer.matching.weight': 'Weight (kg)',
    'customer.matching.volume': 'Volume (m³)',
    'customer.matching.category': 'Category',
    'customer.matching.radius': 'Search Radius (km)',
    'customer.matching.matched_drivers': 'Matched Drivers (${count})',
    'customer.matching.compatibility_score': 'Compatibility Score: ${score}%',

    // NOTIFICATIONS
    'customer.notifications.title': 'Notifications',
    'customer.notifications.all': 'All',
    'customer.notifications.unread': 'Unread',
    'customer.notifications.orders': 'Orders',
    'customer.notifications.payments': 'Payments',
    'customer.notifications.system': 'System',
    'customer.notifications.settings': 'Settings',
    'customer.notifications.no_notifications': 'No notifications',
    'customer.notifications.no_unread': 'All caught up! No unread notifications.',
    'customer.notifications.mark_all_read': 'Mark All Read',

    // CUSTOMER PROFILE TABS
    'customer.profile.tab.personal': 'Personal',
    'customer.profile.tab.addresses': 'Addresses',
    'customer.profile.tab.payment': 'Payment',
    'customer.profile.tab.preferences': 'Preferences',
    'customer.profile.tab.stats': 'Statistics',

    // ADDITIONAL CUSTOMER UI KEYS
    'customer.dashboard.title': 'Customer Dashboard',
    'customer.dashboard.welcome': 'Welcome back, Customer!',
    'customer.dashboard.active_orders': 'Active Orders',
    'customer.dashboard.completed_orders': 'Completed Orders',
    'customer.dashboard.total_spent': 'Total Spent',
    'customer.dashboard.create_order': 'Create New Order',
    'customer.dashboard.view_all': 'View All Orders',
    'customer.dashboard.no_orders': 'No active orders',
    'customer.dashboard.get_started': 'Create your first delivery order',

    // ORDER STATUS
    'customer.order_status.pending': 'Pending',
    'customer.order_status.matched': 'Matched',
    'customer.order_status.accepted': 'Accepted',
    'customer.order_status.in_progress': 'In Progress',
    'customer.order_status.completed': 'Completed',
    'customer.order_status.cancelled': 'Cancelled',

    // PAYMENT METHODS
    'customer.payment.methods.card': 'Credit Card',
    'customer.payment.methods.cash': 'Cash',
    'customer.payment.methods.wallet': 'Wallet',
    'customer.payment.status.pending': 'Pending',
    'customer.payment.status.completed': 'Completed',
    'customer.payment.status.failed': 'Failed',
    'customer.payment.status.refunded': 'Refunded',

    // ADDITIONAL COMMON CUSTOMER UI
    'customer.common.save': 'Save',
    'customer.common.cancel': 'Cancel',
    'customer.common.edit': 'Edit',
    'customer.common.delete': 'Delete',
    'customer.common.confirm': 'Confirm',
    'customer.common.yes': 'Yes',
    'customer.common.no': 'No',
    'customer.common.loading': 'Loading...',
    'customer.common.error': 'Error',
    'customer.common.success': 'Success',
    'customer.common.warning': 'Warning',
    'customer.common.info': 'Information',

    // SUPPORT & HELP
    'customer.support.title': 'Support Center',
    'customer.support.faq': 'Frequently Asked Questions',
    'customer.support.contact_us': 'Contact Us',
    'customer.support.live_chat': 'Live Chat',
    'customer.support.help_center': 'Help Center',

    // REVIEWS & RATINGS
    'customer.reviews.title': 'My Reviews',
    'customer.reviews.leave_review': 'Leave a Review',
    'customer.reviews.driver_rating': 'Driver Rating',
    'customer.reviews.service_rating': 'Service Rating',
    'customer.reviews.submit_review': 'Submit Review',

    // SETTINGS
    'customer.settings.title': 'Settings',
    'customer.settings.account': 'Account Settings',
    'customer.settings.notifications': 'Notification Settings',
    'customer.settings.privacy': 'Privacy Settings',
    'customer.booking.category_documents': 'Documents & Small Packages',
    'customer.booking.category_furniture': 'Furniture & Appliances',
    'customer.booking.category_construction': 'Construction Materials',
    'customer.booking.category_food': 'Food & Beverages',
    'customer.booking.category_electronics': 'Electronics & Fragile Items',
    'customer.booking.category_other': 'Other',
    'customer.booking.price_calculated_success': 'Price calculated successfully!',
    'customer.booking.price_calculation_failed': 'Failed to calculate price',
    'customer.booking.service_connection_failed': 'Failed to connect to pricing service',
    'customer.booking.ready_to_book': 'Ready to book! Estimated price: $${price}',
    'customer.booking.estimated_price': 'Estimated Price',
    'customer.booking.distance': 'Distance',
    'customer.booking.estimated_time': 'Est. time',
    'customer.booking.confidence_interval': 'Confidence interval: $${low} - $${high}',
    'customer.booking.fill_all_fields_to_see_price': 'Fill in all fields to see price estimate',
    'customer.booking.pickup_address_placeholder': 'Enter pickup address',
    'customer.booking.delivery_address_placeholder': 'Enter delivery address',
    'customer.booking.select_category': 'Select category',
    'customer.booking.weight_placeholder': 'e.g., 5.5',
    'customer.booking.volume_placeholder': 'e.g., 0.5',
    'customer.booking.urgency_standard': 'Standard (same day)',
    'customer.booking.urgency_urgent': 'Urgent (within 2 hours)',
    'customer.booking.urgency_scheduled': 'Scheduled (next day)',
    'customer.booking.fill_all_fields_to_book': 'Fill all fields to see price',
    'customer.booking.price_updates_automatically': 'Price updates automatically as you fill the form',
    'customer.booking.ai_powered_prediction': 'Using AI-powered delivery cost prediction with 81% accuracy',
    'customer.bulk.template_downloaded': 'Excel template downloaded! Fill in: Pickup Address, Delivery Address, Weight (kg), Volume (m³), Category, Urgency',
    'customer.bulk.booking_confirmed': 'Bulk Booking Confirmed!',
    'customer.bulk.orders_placed': 'Orders Placed',
    'customer.bulk.upload_another_batch': 'Upload Another Batch',
    'customer.bulk.optimization_results': 'Optimization Results',
    'customer.bulk.total_orders': 'Total Orders',
    'customer.bulk.vehicles_needed': 'Vehicles Needed',
    'customer.bulk.total_distance': 'Total Distance',
    'customer.bulk.co2_reduced': 'CO₂ Reduced',
    'customer.bulk.optimized_routes': 'Optimized Routes',
    'customer.bulk.utilization': 'Utilization',
    'customer.bulk.back_to_review': 'Back to Review',
    'customer.bulk.review_description': 'Review and edit your bulk orders before optimization',
    'customer.bulk.order_id': 'Order ID',
    'customer.bulk.pickup': 'Pickup',
    'customer.bulk.delivery': 'Delivery',
    'customer.bulk.weight': 'Weight',
    'customer.bulk.volume': 'Volume',
    'customer.bulk.category': 'Category',
    'customer.bulk.cost': 'Cost',
    'customer.bulk.summary': 'Summary',
    'customer.bulk.total_weight': 'Total Weight',
    'customer.bulk.total_volume': 'Total Volume',
    'customer.bulk.estimated_cost': 'Estimated Cost',
    'customer.bulk.upload_different_file': 'Upload Different File',
    'customer.bulk.need_template': 'Need a template?',
    'customer.bulk.template_description': 'Download our Excel template with the required format',
    'customer.bulk.upload_excel_file': 'Upload your Excel file',
    'customer.bulk.file_support': 'Support for .xlsx, .xls files up to 10MB',
    'customer.bulk.uploaded': 'Uploaded: ${filename}',
    'customer.bulk.required_excel_format': 'Required Excel Format:',
    'customer.bulk.required_columns': 'Required Columns:',
    'customer.bulk.column_pickup': 'Pickup Address',
    'customer.bulk.column_delivery': 'Delivery Address',
    'customer.bulk.column_weight': 'Weight (kg)',
    'customer.bulk.column_volume': 'Volume (m³)',
    'customer.bulk.column_category': 'Category',
    'customer.bulk.column_urgency': 'Urgency (standard/urgent)',
    'customer.bulk.supported_categories': 'Supported Categories:',
    'customer.bulk.category_documents': 'Documents',
    'customer.bulk.category_furniture': 'Furniture',
    'customer.bulk.category_construction': 'Construction',
    'customer.bulk.category_electronics': 'Electronics',
    'customer.bulk.category_food': 'Food & Beverages',
    'customer.bulk.category_other': 'Other',
    'customer.bulk.benefits_title': 'Bulk Booking Benefits:',
    'customer.bulk.benefit_1': 'Automatic route optimization',
    'customer.bulk.benefit_2': 'Volume discounts available',
    'customer.bulk.benefit_3': 'Efficient vehicle utilization',
    'customer.bulk.benefit_4': 'Reduced delivery costs',
    'customer.bulk.benefit_5': 'Environmental impact reduction',
    'customer.profile.invalid_image': 'Please select an image file',
    'customer.profile.image_too_large': 'Image size should be less than 5MB',
    'customer.profile.picture_uploaded': 'Profile picture uploaded successfully',
    'customer.profile.personal_info_updated': 'Personal information updated successfully',
    'customer.profile.business_info_updated': 'Business information updated successfully',
    'customer.profile.fill_all_address_fields': 'Please fill all required address fields',
    'customer.profile.address_added': 'Address added successfully',
    'customer.profile.address_updated': 'Address updated successfully',
    'customer.profile.cannot_delete_only_address': 'Cannot delete the only address',
    'customer.profile.address_deleted': 'Address deleted successfully',
    'customer.profile.default_address_updated': 'Default address updated',
    'customer.profile.account_type_changed': 'Account type changed to ${type}',
    'customer.profile.retry_loading': 'Retry Loading',
    'customer.profile.no_profile': 'No Profile Found',
    'customer.profile.complete_onboarding': 'Complete onboarding to create your customer profile',
    'customer.profile.go_to_onboarding': 'Go to Onboarding',
    'customer.profile.change_picture': 'Change profile picture',
    'customer.profile.personal_account': 'Personal Account',
    'customer.profile.orders': 'orders',
    'customer.profile.account_type': 'Account Type',
    'customer.profile.tab.business': 'Business',
    'customer.profile.first_name': 'First Name',
    'customer.profile.last_name': 'Last Name',
    'customer.profile.email': 'Email',
    'customer.profile.phone': 'Phone Number',
    'customer.profile.date_of_birth': 'Date of Birth',
    'customer.profile.select_business_type': 'Select business type',
    'customer.profile.business_type_retail': 'Retail Store',
    'customer.profile.business_type_food': 'Restaurant/Food Service',
    'customer.profile.business_type_ecommerce': 'E-commerce',
    'customer.profile.business_type_manufacturing': 'Manufacturing',
    'customer.profile.business_type_healthcare': 'Healthcare',
    'customer.profile.business_type_education': 'Education',
    'customer.profile.business_type_construction': 'Construction',
    'customer.profile.business_type_professional': 'Professional Services',
    'customer.profile.business_type_other': 'Other',
    'customer.profile.add_new_address': 'Add New Address',
    'customer.profile.label': 'Label',
    'customer.profile.label_home': 'Home',
    'customer.profile.label_office': 'Office',
    'customer.profile.label_business': 'Business',
    'customer.profile.label_other': 'Other',
    'customer.profile.street_address': 'Street Address',
    'customer.profile.street_address_placeholder': '123 Main St',
    'customer.profile.city': 'City',
    'customer.profile.city_placeholder': 'New York',
    'customer.profile.state': 'State',
    'customer.profile.state_placeholder': 'NY',
    'customer.profile.zip_code': 'ZIP Code',
    'customer.profile.zip_code_placeholder': '10001',
    'customer.profile.set_as_default': 'Set as default address',
    'customer.profile.notes': 'Notes',
    'customer.profile.optional': 'Optional',
    'customer.profile.notes_placeholder': 'Any special instructions for delivery',
    'customer.profile.no_addresses': 'No addresses saved yet',
    'customer.profile.add_first_address': 'Add Your First Address',
    'customer.profile.default_badge': 'Default',
    'customer.profile.inactive_badge': 'Inactive',
    'customer.profile.note': 'Note',
    'customer.profile.set_default_button': 'Set Default',
    'customer.profile.delete_address_title': 'Delete Address',
    'customer.profile.delete_address_description': 'Are you sure you want to delete this address? This action cannot be undone.',
    'customer.profile.payment_setup_info': 'Payment method setup would open here',
    'customer.profile.payment_integration_info': 'Payment methods integration would be implemented separately',
    'customer.profile.payment_service_info': 'This would connect to a payment service like Stripe',
    'customer.profile.connect_payment_method': 'Connect Payment Method',
    'customer.profile.notification_preferences': 'Notification Preferences',
    'customer.profile.email_notifications': 'Email Notifications',
    'customer.profile.email_notifications_desc': 'Order updates, receipts, and newsletters',
    'customer.profile.email_preference_updated': 'Email notification preference updated',
    'customer.profile.sms_notifications': 'SMS Notifications',
    'customer.profile.sms_notifications_desc': 'Real-time delivery updates',
    'customer.profile.sms_preference_updated': 'SMS notification preference updated',
    'customer.profile.push_notifications': 'Push Notifications',
    'customer.profile.push_notifications_desc': 'In-app notifications',
    'customer.profile.push_preference_updated': 'Push notification preference updated',
    'customer.profile.privacy_preferences': 'Privacy Preferences',
    'customer.profile.location_preference_updated': 'Location sharing preference updated',
    'customer.profile.analytics_preference_updated': 'Usage analytics preference updated',
    'customer.profile.marketing_preference_updated': 'Marketing emails preference updated',
    'customer.profile.customer_service': 'Customer Service',
    'customer.profile.membership_level': 'Membership Level',
    'customer.profile.account_status': 'Account Status',
    'customer.profile.active_since': 'Active since ${date}',
    'customer.profile.address_management': 'Address Management',
    'customer.profile.saved_addresses_count': 'saved address(es)',
    'customer.profile.address_count': 'Address(es)',
    'customer.profile.account_type_stat': 'Account Type',
    'customer.profile.business_account_full': 'Business Account with full features',
    'customer.profile.personal_account_desc': 'Personal Account',
    'customer.profile.business': 'Business',
  },
  
  ru: {
    // Common
    'app.name': 'ДоставкаМэтч',
    'common.loading': 'Загрузка...',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.add': 'Добавить',
    'common.remove': 'Удалить',
    'common.close': 'Закрыть',
    'common.submit': 'Отправить',
    'common.next': 'Далее',
    'common.previous': 'Назад',
    'common.back': 'Назад',
    'common.continue': 'Продолжить',
    'common.confirm': 'Подтвердить',
    'common.yes': 'Да',
    'common.no': 'Нет',
    'common.ok': 'ОК',
    'common.search': 'Поиск',
    'common.filter': 'Фильтр',
    'common.sort': 'Сортировка',
    'common.view': 'Просмотр',
    'common.upload': 'Загрузить',
    'common.download': 'Скачать',
    'common.print': 'Печать',
    'common.share': 'Поделиться',
    'common.copy': 'Копировать',
    'common.paste': 'Вставить',
    'common.cut': 'Вырезать',
    'common.undo': 'Отменить',
    'common.redo': 'Повторить',
    'common.select_all': 'Выбрать всё',
    'common.clear': 'Очистить',
    'common.reset': 'Сбросить',
    'common.refresh': 'Обновить',
    'common.update': 'Обновить',
    'common.create': 'Создать',
    'common.new': 'Новый',
    'common.open': 'Открыть',
    'common.start': 'Начать',
    'common.stop': 'Остановить',
    'common.pause': 'Пауза',
    'common.resume': 'Продолжить',
    'common.finish': 'Завершить',
    'common.complete': 'Завершить',
    'common.pending': 'Ожидание',
    'common.approved': 'Одобрено',
    'common.rejected': 'Отклонено',
    'common.expired': 'Истекло',
    'common.active': 'Активный',
    'common.inactive': 'Неактивный',
    'common.enabled': 'Включено',
    'common.disabled': 'Отключено',
    'common.available': 'Доступно',
    'common.unavailable': 'Недоступно',
    'common.online': 'Онлайн',
    'common.offline': 'Офлайн',
    'common.connected': 'Подключено',
    'common.disconnected': 'Отключено',
    'common.success': 'Успех',
    'common.error': 'Ошибка',
    'common.warning': 'Предупреждение',
    'common.info': 'Информация',
    'common.help': 'Помощь',
    'common.support': 'Поддержка',
    'common.contact': 'Контакты',
    'common.about': 'О нас',
    'common.privacy': 'Конфиденциальность',
    'common.terms': 'Условия',
    'common.settings': 'Настройки',
    'common.preferences': 'Предпочтения',
    'common.profile': 'Профиль',
    'common.account': 'Аккаунт',
    'common.dashboard': 'Панель управления',
    'common.home': 'Главная',
    'common.logout': 'Выйти',
    'common.login': 'Войти',
    'common.signup': 'Регистрация',
    'common.signin': 'Войти',
    'common.email': 'Email',
    'common.password': 'Пароль',
    'common.username': 'Имя пользователя',
    'common.name': 'Имя',
    'common.first_name': 'Имя',
    'common.last_name': 'Фамилия',
    'common.phone': 'Телефон',
    'common.address': 'Адрес',
    'common.city': 'Город',
    'common.state': 'Регион',
    'common.country': 'Страна',
    'common.zip_code': 'Почтовый индекс',
    'common.date': 'Дата',
    'common.time': 'Время',
    'common.today': 'Сегодня',
    'common.yesterday': 'Вчера',
    'common.tomorrow': 'Завтра',
    'common.week': 'Неделя',
    'common.month': 'Месяц',
    'common.year': 'Год',
    'common.hour': 'Час',
    'common.minute': 'Минута',
    'common.second': 'Секунда',
    'common.price': 'Цена',
    'common.cost': 'Стоимость',
    'common.total': 'Итого',
    'common.subtotal': 'Промежуточный итог',
    'common.tax': 'Налог',
    'common.discount': 'Скидка',
    'common.fee': 'Комиссия',
    'common.amount': 'Сумма',
    'common.quantity': 'Количество',
    'common.weight': 'Вес',
    'common.size': 'Размер',
    'common.dimension': 'Размер',
    'common.length': 'Длина',
    'common.width': 'Ширина',
    'common.height': 'Высота',
    'common.volume': 'Объём',
    'common.description': 'Описание',
    'common.note': 'Заметка',
    'common.comment': 'Комментарий',
    'common.message': 'Сообщение',
    'common.notification': 'Уведомление',
    'common.alert': 'Предупреждение',
    'common.reminder': 'Напоминание',
    'common.language': 'Язык',

    // Header
    'header.driver': 'Водитель',
    'header.customer': 'Клиент',

    // Landing Page
    'landing.title': 'Умная платформа доставки',
    'landing.subtitle': 'Связывайтесь с проверенными водителями для эффективной доставки товаров. От отдельных посылок до массовых отправлений, наша платформа с ИИ оптимизирует маршруты и снижает расходы.',
    'landing.get_started': 'Начать',
    'landing.ship_now': 'Отправить сейчас',
    'landing.drive_earn': 'Возить и зарабатывать',
    'landing.stats.drivers': 'Активных водителей',
    'landing.stats.deliveries': 'Доставок выполнено',
    'landing.stats.cities': 'Городов охвачено',
    'landing.stats.rating': 'Средний рейтинг',
    'landing.features.title': 'Почему стоит выбрать ДоставкаМэтч?',
    'landing.features.subtitle': 'Создано для эффективности, разработано для масштаба. Наша платформа революционизирует способ перемещения товаров из точки А в точку Б.',
    'landing.features.smart_matching.title': 'Умный подбор',
    'landing.features.smart_matching.desc': 'Алгоритм с ИИ подбирает заказы к наиболее подходящим водителям на основе грузоподъёмности, близости расположения и оптимизации маршрута.',
    'landing.features.bulk_orders.title': 'Массовые заказы',
    'landing.features.bulk_orders.desc': 'Загружайте несколько доставок через Excel и получайте оптимизированное планирование маршрутов, которое экономит время и топливо.',
    'landing.features.real_time_tracking.title': 'Отслеживание в реальном времени',
    'landing.features.real_time_tracking.desc': 'Отслеживайте свои доставки в реальном времени с живыми GPS-обновлениями и мгновенными уведомлениями.',
    'landing.features.secure_reliable.title': 'Безопасно и надёжно',
    'landing.features.secure_reliable.desc': 'Проверенные водители, безопасные платежи и комплексное страховое покрытие для спокойствия.',
    'landing.how_it_works.title': 'Как это работает',
    'landing.how_it_works.subtitle': 'Простые шаги для запуска вашей доставки',
    'landing.how_it_works.customers': 'Для клиентов',
    'landing.how_it_works.drivers': 'Для водителей',
    'landing.how_it_works.customer_step1': 'Создать запрос',
    'landing.how_it_works.customer_step1_desc': 'Введите детали забора и доставки',
    'landing.how_it_works.customer_step2': 'Найти подходящего',
    'landing.how_it_works.customer_step2_desc': 'ИИ находит лучшего водителя для вас',
    'landing.how_it_works.customer_step3': 'Отслеживать и получить',
    'landing.how_it_works.customer_step3_desc': 'Обновления в реальном времени до доставки',
    'landing.how_it_works.driver_step1': 'Зарегистрироваться и подтвердить',
    'landing.how_it_works.driver_step1_desc': 'Загрузите документы и информацию о транспорте',
    'landing.how_it_works.driver_step2': 'Получать заказы',
    'landing.how_it_works.driver_step2_desc': 'Принимайте близлежащие запросы на доставку',
    'landing.how_it_works.driver_step3': 'Зарабатывать деньги',
    'landing.how_it_works.driver_step3_desc': 'Выполняйте доставки и получайте оплату',
    'landing.cta.title': 'Готовы начать?',
    'landing.cta.subtitle': 'Присоединяйтесь к тысячам клиентов и водителей, которые доверяют ДоставкаМэтч для своих потребностей в доставке.',
    'landing.cta.button': 'Начать первую доставку',
    'landing.footer.subtitle': 'Соединяем водителей и клиентов для эффективной доставки товаров.',

    // Auth Page
    'auth.title': 'ДоставкаМэтч',
    'auth.login.welcome': 'Добро пожаловать!',
    'auth.signup.welcome': 'Создайте свой аккаунт',
    'auth.login': 'Войти',
    'auth.signup': 'Регистрация',
    'auth.account_type': 'Я хочу:',
    'auth.customer_option': 'Отправлять товары и посылки',
    'auth.driver_option': 'Возить и зарабатывать',
    'auth.confirm_password': 'Подтвердите пароль',
    'auth.agree_terms': 'Я согласен с Условиями обслуживания и Политикой конфиденциальности',
    'auth.forgot_password': 'Забыли пароль?',
    'auth.no_account': 'Нет аккаунта?',
    'auth.have_account': 'Уже есть аккаунт?',
    'auth.demo_access': 'Быстрый демо-доступ:',
    'auth.demo_customer': 'Демо клиент',
    'auth.demo_driver': 'Демо водитель',

    // Driver Dashboard
    'driver.dashboard.title': 'Панель водителя',
    'driver.dashboard.welcome': 'Добро пожаловать, водитель!',
    'driver.dashboard.status': 'Статус',
    'driver.dashboard.available': 'Доступен',
    'driver.dashboard.busy': 'Занят',
    'driver.dashboard.go_online': 'Выйти в сеть',
    'driver.dashboard.go_offline': 'Уйти в офлайн',
    'driver.dashboard.today_earnings': 'Заработок сегодня',
    'driver.dashboard.active_orders': 'Активные заказы',
    'driver.dashboard.completion_rate': 'Процент выполнения',
    'driver.dashboard.rating': 'Ваш рейтинг',
    'driver.dashboard.available_orders': 'Доступные заказы',
    'driver.dashboard.no_orders': 'Сейчас нет доступных заказов',
    'driver.dashboard.check_back': 'Проверьте снова через несколько минут для новых запросов на доставку.',
    'driver.dashboard.accept_order': 'Принять заказ',
    'driver.dashboard.pickup': 'Забрать',
    'driver.dashboard.delivery': 'Доставка',
    'driver.dashboard.earnings': 'Заработок',
    'driver.dashboard.distance': 'Расстояние',
    'driver.dashboard.quick_stats': 'Быстрая статистика',
    'driver.dashboard.this_week': 'На этой неделе',
    'driver.dashboard.deliveries': 'Доставки',
    'driver.dashboard.hours_online': 'Часов онлайн',

    // Navigation Tabs
    'nav.dashboard': 'Панель управления',
    'nav.orders': 'Активные заказы',
    'nav.earnings': 'Заработок',
    'nav.notifications': 'Уведомления',
    'nav.profile': 'Профиль',
    'nav.booking': 'Новый заказ',
    'nav.bulk': 'Массовая загрузка',
    'nav.tracking': 'Отслеживание заказов',
    'nav.matching': 'Поиск водителей',

    // Notifications
    'notifications.title': 'Уведомления',
    'notifications.unread': 'непрочитанных уведомлений',
    'notifications.all_caught_up': 'Все прочитано!',
    'notifications.mark_all_read': 'Отметить все как прочитанные',
    'notifications.all': 'Все',
    'notifications.unread_tab': 'Непрочитанные',
    'notifications.orders': 'Заказы',
    'notifications.payments': 'Платежи',
    'notifications.system': 'Система',
    'notifications.settings': 'Настройки',
    'notifications.preferences': 'Настройки уведомлений',
    'notifications.preferences_desc': 'Выберите, какие уведомления вы хотите получать',
    'notifications.types': 'Типы уведомлений',
    'notifications.order_updates': 'Обновления заказов',
    'notifications.order_updates_desc': 'Новые заказы, изменения статуса, завершения',
    'notifications.payment_notifications': 'Уведомления о платежах',
    'notifications.payment_notifications_desc': 'Подтверждения платежей, обновления заработка',
    'notifications.system_updates': 'Системные обновления',
    'notifications.system_updates_desc': 'Обновления приложения, уведомления о техническом обслуживании',
    'notifications.promotions': 'Акции и советы',
    'notifications.promotions_desc': 'Специальные предложения, советы по вождению, обновления платформы',
    'notifications.delivery_methods': 'Способы доставки',
    'notifications.email_notifications': 'Email уведомления',
    'notifications.email_notifications_desc': 'Получать уведомления по электронной почте',
    'notifications.sms_notifications': 'SMS уведомления',
    'notifications.sms_notifications_desc': 'Получать уведомления по SMS',
    'notifications.push_notifications': 'Push-уведомления',
    'notifications.push_notifications_desc': 'Получать уведомления в приложении',
    'notifications.no_notifications': 'Нет уведомлений',
    'notifications.no_unread': 'Все прочитано! Нет непрочитанных уведомлений.',
    'notifications.no_category': 'Нет уведомлений в этой категории.',

    // Driver Profile
    'driver.profile.title': 'Профиль водителя',
    'driver.profile.approved_drive': 'Разрешено к вождению',
    'driver.profile.cannot_drive': 'Нельзя водить',
    'driver.profile.completion': 'Заполненность профиля',
    'driver.profile.personal_info': 'Личная информация',
    'driver.profile.vehicle_info': 'Информация о транспорте',
    'driver.profile.documents': 'Документы',
    'driver.profile.statistics': 'Статистика',
    'driver.profile.edit_profile': 'Редактировать профиль',
    'driver.profile.save_changes': 'Сохранить изменения',
    'driver.profile.edit_vehicle': 'Редактировать транспорт',
    'driver.profile.date_birth': 'Дата рождения',
    'driver.profile.member_since': 'Участник с',
    'driver.profile.vehicle_type': 'Тип транспорта',
    'driver.profile.license_plate': 'Номерной знак',
    'driver.profile.make': 'Марка',
    'driver.profile.model': 'Модель',
    'driver.profile.year': 'Год',
    'driver.profile.color': 'Цвет',
    'driver.profile.max_weight': 'Макс. вес (кг)',
    'driver.profile.max_volume': 'Макс. объём (м³)',
    'driver.profile.update_photo': 'Обновить фото',
    'driver.profile.required_documents': 'Обязательные документы',
    'driver.profile.documents_desc': 'Поддерживайте документы в актуальном состоянии для продолжения работы',
    'driver.profile.action_required': 'Требуются действия',
    'driver.profile.document_issues': 'Вы не можете принимать заказы, пока не решите все проблемы с документами. Пожалуйста, загрузите или обновите просроченные документы.',
    'driver.profile.driver_license': 'Водительские права',
    'driver.profile.auto_insurance': 'Автострахование',
    'driver.profile.vehicle_registration': 'Регистрация транспорта',
    'driver.profile.vehicle_inspection': 'Техосмотр транспорта',
    'driver.profile.uploaded': 'Загружено',
    'driver.profile.expires': 'Истекает',
    'driver.profile.rejected': 'Отклонено',
    'driver.profile.reupload': 'Загрузить заново',
    'driver.profile.upload_document': 'Загрузить документ',
    'driver.profile.upload_desc': 'Пожалуйста, загрузите новый документ {document}. Убедитесь, что он чёткий и не просроченный.',
    'driver.profile.stats.total_deliveries': 'Всего доставок',
    'driver.profile.stats.average_rating': 'Средний рейтинг',
    'driver.profile.stats.total_earnings': 'Общий заработок',
    'driver.profile.stats.completion_rate': 'Процент выполнения',
    'driver.profile.verification': 'Статус верификации',
    'driver.profile.background_check': 'Проверка данных',
    'driver.profile.driving_authorization': 'Разрешение на вождение',
    'driver.profile.authorized': 'Разрешено',
    'driver.profile.suspended': 'Приостановлено',

    // Customer Profile
    'customer.profile.title': 'Профиль клиента',
    'customer.profile.business_account': 'Бизнес-аккаунт',
    'customer.profile.personal_account': 'Личный аккаунт',
    'customer.profile.member_since': 'Участник с',
    'customer.profile.personal': 'Личное',
    'customer.profile.addresses': 'Адреса',
    'customer.profile.payment': 'Платежи',
    'customer.profile.preferences': 'Предпочтения',
    'customer.profile.statistics': 'Статистика',
    'customer.profile.personal_info': 'Личная информация',
    'customer.profile.business_info': 'Информация о бизнесе',
    'customer.profile.business_name': 'Название компании',
    'customer.profile.business_type': 'Тип бизнеса',
    'customer.profile.business_address': 'Адрес компании',
    'customer.profile.business_phone': 'Телефон компании',
    'customer.profile.tax_id': 'Налоговый номер',
    'customer.profile.saved_addresses': 'Сохранённые адреса',
    'customer.profile.add_address': 'Добавить адрес',
    'customer.profile.default': 'По умолчанию',
    'customer.profile.set_default': 'Установить по умолчанию',
    'customer.profile.delete_address': 'Удалить адрес',
    'customer.profile.delete_address_confirm': 'Вы уверены, что хотите удалить этот адрес? Это действие нельзя отменить.',
    'customer.profile.payment_methods': 'Способы оплаты',
    'customer.profile.add_payment_method': 'Добавить способ оплаты',
    'customer.profile.remove_payment_method': 'Удалить способ оплаты',
    'customer.profile.remove_payment_confirm': 'Вы уверены, что хотите удалить этот способ оплаты? Это действие нельзя отменить.',
    'customer.profile.notification_prefs': 'Настройки уведомлений',
    'customer.profile.privacy_prefs': 'Настройки конфиденциальности',
    'customer.profile.share_location': 'Делиться данными о местоположении',
    'customer.profile.share_location_desc': 'Помочь улучшить оптимизацию маршрутов',
    'customer.profile.share_analytics': 'Делиться аналитикой использования',
    'customer.profile.share_analytics_desc': 'Помочь улучшить платформу',
    'customer.profile.marketing_emails': 'Маркетинговые письма',
    'customer.profile.marketing_emails_desc': 'Рекламные предложения и советы',
    'customer.profile.account_stats': 'Статистика аккаунта',
    'customer.profile.total_orders': 'Всего заказов',
    'customer.profile.total_spent': 'Всего потрачено',
    'customer.profile.average_rating': 'Средний рейтинг',
    'customer.profile.days_active': 'Дней активности',
    'customer.profile.account_benefits': 'Преимущества аккаунта',
    'customer.profile.free_delivery': 'Кредиты бесплатной доставки',
    'customer.profile.loyalty_points': 'Баллы лояльности',
    'customer.profile.bulk_discount': 'Скидка за объём',

    // Earnings
    'earnings.title': 'Заработок и платежи',
    'earnings.subtitle': 'Управляйте своими доходами и способами оплаты',
    'earnings.withdraw_funds': 'Вывести средства',
    'earnings.available_balance': 'Доступный баланс',
    'earnings.pending_payments': 'Ожидающие платежи',
    'earnings.this_week': 'На этой неделе',
    'earnings.total_earned': 'Всего заработано',
    'earnings.overview': 'Обзор',
    'earnings.transactions': 'История транзакций',
    'earnings.payment_methods': 'Способы оплаты',
    'earnings.how_paid': 'Как вы получаете оплату',
    'earnings.complete_delivery': 'Завершить доставку',
    'earnings.complete_delivery_desc': 'Клиент подтверждает доставку и обрабатывается платёж',
    'earnings.payment_options': 'Варианты оплаты',
    'earnings.cash_immediate': 'Наличные: Оставить себе сразу (сообщить в приложении)',
    'earnings.card_digital': 'Карта/Цифровой: Добавлено к вашему балансу',
    'earnings.automatic_payouts': 'Автоматические выплаты',
    'earnings.daily_transfers': 'Ежедневные автоматические переводы в ваш банк',
    'earnings.weekly_transfers': 'Еженедельные автоматические переводы в ваш банк',
    'earnings.instant_transfers': 'Мгновенные переводы доступны',
    'earnings.next_payout': 'Следующая выплата',
    'earnings.recent_activity': 'Недавняя активность',
    'earnings.withdraw_title': 'Вывести заработок',
    'earnings.payment_method': 'Способ оплаты',
    'earnings.select_payment_method': 'Выберите способ оплаты',
    'earnings.minimum_withdrawal': 'Минимальный вывод',
    'earnings.processing_time': 'Время обработки: 1-3 рабочих дня',
    'earnings.no_fees': 'Нет комиссии за банковские переводы',
    'earnings.process_withdrawal': 'Обработать вывод',
    'earnings.add_payment_method': 'Добавить способ оплаты',
    'earnings.cash_payments': 'Наличные платежи',
    'earnings.cash_instructions': 'Инструкции по наличным платежам',
    'earnings.cash_collect': 'Получайте наличную оплату напрямую от клиентов',
    'earnings.cash_receipt': 'Всегда предоставляйте чек по запросу',
    'earnings.cash_report': 'Сообщайте о наличном заработке в приложении сразу после доставки',
    'earnings.cash_safe': 'Держите наличные в безопасности и регулярно сдавайте в банк',
    'earnings.cash_no_withdraw': 'Наличный заработок добавляется к общему, но не требует вывода',
    'earnings.add_payment_title': 'Добавить способ оплаты',
    'earnings.add_payment_desc': 'Добавьте новый способ получения ваших доходов',
    'earnings.payment_type': 'Тип платежа',
    'earnings.bank_account': 'Банковский счёт',
    'earnings.digital_wallet': 'Цифровой кошелёк (PayPal и др.)',
    'earnings.account_name': 'Название счёта',
    'earnings.account_details': 'Реквизиты счёта',

    // Units and measurements
    'units.kg': 'кг',
    'units.m3': 'м³',
    'units.km': 'км',
    'units.minutes': 'минут',
    'units.hours': 'часов',
    'units.days': 'дней',

    // Status and states
    'status.pending': 'Ожидание',
    'status.approved': 'Одобрено',
    'status.rejected': 'Отклонено',
    'status.expired': 'Истекло',
    'status.completed': 'Завершено',
    'status.processing': 'Обработка',
    'status.failed': 'Неудача',
    'status.active': 'Активный',
    'status.inactive': 'Неактивный',
    // =============== CUSTOMER UI TRANSLATIONS ===============
    // CUSTOMER BOOKING
    'customer.booking.title': 'Калькулятор стоимости доставки',
    'customer.booking.subtitle': 'Получите мгновенную оценку стоимости вашей доставки',
    'customer.booking.price_estimate': 'Заполните все поля для оценки стоимости',
    'customer.booking.pickup_address': 'Адрес забора',
    'customer.booking.delivery_address': 'Адрес доставки',
    'customer.booking.item_category': 'Категория товара',
    'customer.booking.weight': 'Вес (кг)',
    'customer.booking.volume': 'Объём (м³)',
    'customer.booking.urgency': 'Срочность доставки',
    'customer.booking.special_requirements': 'Особые требования',
    'customer.booking.fragile': 'Хрупкие предметы',
    'customer.booking.refrigerated': 'Охлаждаемые',
    'customer.booking.oversized': 'Крупногабаритные',
    'customer.booking.hazardous': 'Опасные грузы',
    'customer.booking.book_delivery': 'Забронировать доставку за ${amount}',
    'customer.booking.fill_all_fields': 'Заполните все поля для отображения цены',
    'customer.booking.calculating': 'Расчёт...',

    // BULK BOOKING
    'customer.bulk.title': 'Массовая загрузка заказов',
    'customer.bulk.subtitle': 'Загрузите несколько заказов одновременно с помощью файла Excel',
    'customer.bulk.download_template': 'Скачать шаблон',
    'customer.bulk.choose_file': 'Выбрать файл',
    'customer.bulk.upload_success': 'Загружено: ${filename}',
    'customer.bulk.processing': 'Обработка...',
    'customer.bulk.review_orders': 'Просмотреть заказы (${count})',
    'customer.bulk.optimize_routes': 'Оптимизировать маршруты',
    'customer.bulk.confirm_booking': 'Подтвердить бронирование',
    'customer.bulk.orders_placed': 'Заказов размещено',
    'customer.bulk.vehicles_assigned': 'Транспорта назначено',
    'customer.bulk.total_cost': 'Общая стоимость',
    'customer.bulk.fuel_savings': 'Экономия топлива',

    // ORDER TRACKING
    'customer.tracking.my_orders': 'Мои заказы',
    'customer.tracking.your_orders': 'Ваши заказы',
    'customer.tracking.progress': 'Прогресс',
    'customer.tracking.eta': 'Время прибытия: ${time}',
    'customer.tracking.driver_info': 'Информация о водителе',
    'customer.tracking.pickup_address': 'Адрес забора',
    'customer.tracking.delivery_address': 'Адрес доставки',
    'customer.tracking.order_timeline': 'Временная шкала заказа',
    'customer.tracking.mark_delivered': 'Отметить как доставленное',
    'customer.tracking.rate_driver': 'Оценить водителя',

    // MATCHING ENGINE
    'customer.matching.title': 'Система подбора водителей',
    'customer.matching.subtitle': 'Найдите лучших водителей на основе ваших требований',
    'customer.matching.find_drivers': 'Найти водителей',
    'customer.matching.location': 'Место забора',
    'customer.matching.weight': 'Вес (кг)',
    'customer.matching.volume': 'Объём (м³)',
    'customer.matching.category': 'Категория',
    'customer.matching.radius': 'Радиус поиска (км)',
    'customer.matching.matched_drivers': 'Подходящие водители (${count})',
    'customer.matching.compatibility_score': 'Совместимость: ${score}%',

    // NOTIFICATIONS
    'customer.notifications.title': 'Уведомления',
    'customer.notifications.all': 'Все',
    'customer.notifications.unread': 'Непрочитанные',
    'customer.notifications.orders': 'Заказы',
    'customer.notifications.payments': 'Платежи',
    'customer.notifications.system': 'Система',
    'customer.notifications.settings': 'Настройки',
    'customer.notifications.no_notifications': 'Нет уведомлений',
    'customer.notifications.no_unread': 'Все прочитано! Нет непрочитанных уведомлений.',
    'customer.notifications.mark_all_read': 'Отметить все как прочитанные',

    // CUSTOMER PROFILE TABS
    'customer.profile.tab.personal': 'Личное',
    'customer.profile.tab.addresses': 'Адреса',
    'customer.profile.tab.payment': 'Платежи',
    'customer.profile.tab.preferences': 'Предпочтения',
    'customer.profile.tab.stats': 'Статистика',
    'customer.profile.no_profile': 'Профиль не найден',
    'customer.profile.complete_onboarding': 'Завершите регистрацию для создания профиля клиента',
    'customer.profile.go_to_onboarding': 'Перейти к регистрации',

    // ADDITIONAL CUSTOMER UI KEYS
    'customer.dashboard.title': 'Панель клиента',
    'customer.dashboard.welcome': 'Добро пожаловать, клиент!',
    'customer.dashboard.active_orders': 'Активные заказы',
    'customer.dashboard.completed_orders': 'Завершённые заказы',
    'customer.dashboard.total_spent': 'Всего потрачено',
    'customer.dashboard.create_order': 'Создать новый заказ',
    'customer.dashboard.view_all': 'Просмотреть все заказы',
    'customer.dashboard.no_orders': 'Нет активных заказов',
    'customer.dashboard.get_started': 'Создайте свой первый заказ на доставку',

    // ORDER STATUS
    'customer.order_status.pending': 'Ожидание',
    'customer.order_status.matched': 'Подобран',
    'customer.order_status.accepted': 'Принят',
    'customer.order_status.in_progress': 'В процессе',
    'customer.order_status.completed': 'Завершён',
    'customer.order_status.cancelled': 'Отменён',

    // PAYMENT METHODS
    'customer.payment.methods.card': 'Кредитная карта',
    'customer.payment.methods.cash': 'Наличные',
    'customer.payment.methods.wallet': 'Кошелёк',
    'customer.payment.status.pending': 'Ожидание',
    'customer.payment.status.completed': 'Завершён',
    'customer.payment.status.failed': 'Неудача',
    'customer.payment.status.refunded': 'Возвращён',

    // ADDITIONAL COMMON CUSTOMER UI
    'customer.common.save': 'Сохранить',
    'customer.common.cancel': 'Отмена',
    'customer.common.edit': 'Редактировать',
    'customer.common.delete': 'Удалить',
    'customer.common.confirm': 'Подтвердить',
    'customer.common.yes': 'Да',
    'customer.common.no': 'Нет',
    'customer.common.loading': 'Загрузка...',
    'customer.common.error': 'Ошибка',
    'customer.common.success': 'Успех',
    'customer.common.warning': 'Предупреждение',
    'customer.common.info': 'Информация',

    // SUPPORT & HELP
    'customer.support.title': 'Центр поддержки',
    'customer.support.faq': 'Часто задаваемые вопросы',
    'customer.support.contact_us': 'Свяжитесь с нами',
    'customer.support.live_chat': 'Онлайн-чат',
    'customer.support.help_center': 'Центр помощи',

    // REVIEWS & RATINGS
    'customer.reviews.title': 'Мои отзывы',
    'customer.reviews.leave_review': 'Оставить отзыв',
    'customer.reviews.driver_rating': 'Оценка водителя',
    'customer.reviews.service_rating': 'Оценка сервиса',
    'customer.reviews.submit_review': 'Отправить отзыв',

    // SETTINGS
    'customer.settings.title': 'Настройки',
    'customer.settings.account': 'Настройки аккаунта',
    'customer.settings.notifications': 'Настройки уведомлений',
    'customer.settings.privacy': 'Настройки конфиденциальности',
    'customer.booking.category_documents': 'Документы и мелкие посылки',
    'customer.booking.category_furniture': 'Мебель и бытовая техника',
    'customer.booking.category_construction': 'Строительные материалы',
    'customer.booking.category_food': 'Продукты и напитки',
    'customer.booking.category_electronics': 'Электроника и хрупкие предметы',
    'customer.booking.category_other': 'Другое',
    'customer.booking.price_calculated_success': 'Стоимость успешно рассчитана!',
    'customer.booking.price_calculation_failed': 'Не удалось рассчитать стоимость',
    'customer.booking.service_connection_failed': 'Не удалось подключиться к сервису расчета стоимости',
    'customer.booking.ready_to_book': 'Готово к бронированию! Примерная цена: $${price}',
    'customer.booking.estimated_price': 'Примерная цена',
    'customer.booking.distance': 'Расстояние',
    'customer.booking.estimated_time': 'Примерное время',
    'customer.booking.confidence_interval': 'Доверительный интервал: $${low} - $${high}',
    'customer.booking.fill_all_fields_to_see_price': 'Заполните все поля для отображения цены',
    'customer.booking.pickup_address_placeholder': 'Введите адрес забора',
    'customer.booking.delivery_address_placeholder': 'Введите адрес доставки',
    'customer.booking.select_category': 'Выберите категорию',
    'customer.booking.weight_placeholder': 'напр., 5.5',
    'customer.booking.volume_placeholder': 'напр., 0.5',
    'customer.booking.urgency_standard': 'Стандарт (в тот же день)',
    'customer.booking.urgency_urgent': 'Срочно (в течение 2 часов)',
    'customer.booking.urgency_scheduled': 'По расписанию (на следующий день)',
    'customer.booking.fill_all_fields_to_book': 'Заполните все поля для отображения цены',
    'customer.booking.price_updates_automatically': 'Цена обновляется автоматически по мере заполнения формы',
    'customer.booking.ai_powered_prediction': 'Используется ИИ-прогнозирование стоимости доставки с точностью 81%',
    'customer.bulk.template_downloaded': 'Шаблон Excel загружен! Заполните: Адрес забора, Адрес доставки, Вес (кг), Объём (м³), Категория, Срочность',
    'customer.bulk.booking_confirmed': 'Массовое бронирование подтверждено!',
    'customer.bulk.upload_another_batch': 'Загрузить другую партию',
    'customer.bulk.optimization_results': 'Результаты оптимизации',
    'customer.bulk.total_orders': 'Всего заказов',
    'customer.bulk.vehicles_needed': 'Нужно транспорта',
    'customer.bulk.total_distance': 'Общее расстояние',
    'customer.bulk.co2_reduced': 'CO₂ снижено',
    'customer.bulk.optimized_routes': 'Оптимизированные маршруты',
    'customer.bulk.utilization': 'Загрузка',
    'customer.bulk.back_to_review': 'Назад к просмотру',
    'customer.bulk.review_description': 'Просмотрите и отредактируйте массовые заказы перед оптимизацией',
    'customer.bulk.order_id': 'ID заказа',
    'customer.bulk.pickup': 'Забор',
    'customer.bulk.delivery': 'Доставка',
    'customer.bulk.weight': 'Вес',
    'customer.bulk.volume': 'Объём',
    'customer.bulk.category': 'Категория',
    'customer.bulk.cost': 'Стоимость',
    'customer.bulk.summary': 'Сводка',
    'customer.bulk.total_weight': 'Общий вес',
    'customer.bulk.total_volume': 'Общий объём',
    'customer.bulk.estimated_cost': 'Примерная стоимость',
    'customer.bulk.upload_different_file': 'Загрузить другой файл',
    'customer.bulk.need_template': 'Нужен шаблон?',
    'customer.bulk.template_description': 'Скачайте наш шаблон Excel с нужным форматом',
    'customer.bulk.upload_excel_file': 'Загрузите файл Excel',
    'customer.bulk.file_support': 'Поддержка файлов .xlsx, .xls до 10 МБ',
    'customer.bulk.uploaded': 'Загружено: ${filename}',
    'customer.bulk.required_excel_format': 'Требуемый формат Excel:',
    'customer.bulk.required_columns': 'Обязательные колонки:',
    'customer.bulk.column_pickup': 'Адрес забора',
    'customer.bulk.column_delivery': 'Адрес доставки',
    'customer.bulk.column_weight': 'Вес (кг)',
    'customer.bulk.column_volume': 'Объём (м³)',
    'customer.bulk.column_category': 'Категория',
    'customer.bulk.column_urgency': 'Срочность (стандартная/срочная)',
    'customer.bulk.supported_categories': 'Поддерживаемые категории:',
    'customer.bulk.category_documents': 'Документы',
    'customer.bulk.category_furniture': 'Мебель',
    'customer.bulk.category_construction': 'Строительные материалы',
    'customer.bulk.category_electronics': 'Электроника',
    'customer.bulk.category_food': 'Продукты и напитки',
    'customer.bulk.category_other': 'Другое',
    'customer.bulk.benefits_title': 'Преимущества массового бронирования:',
    'customer.bulk.benefit_1': 'Автоматическая оптимизация маршрутов',
    'customer.bulk.benefit_2': 'Доступны скидки за объём',
    'customer.bulk.benefit_3': 'Эффективная загрузка транспорта',
    'customer.bulk.benefit_4': 'Снижение стоимости доставки',
    'customer.bulk.benefit_5': 'Снижение воздействия на окружающую среду',
    'customer.profile.customer': 'Клиент',
    'customer.profile.invalid_image': 'Пожалуйста, выберите файл изображения',
    'customer.profile.image_too_large': 'Размер изображения должен быть менее 5 МБ',
    'customer.profile.picture_uploaded': 'Фото профиля успешно загружено',
    'customer.profile.personal_info_updated': 'Личная информация успешно обновлена',
    'customer.profile.business_info_updated': 'Информация о бизнесе успешно обновлена',
    'customer.profile.fill_all_address_fields': 'Пожалуйста, заполните все обязательные поля адреса',
    'customer.profile.address_added': 'Адрес успешно добавлен',
    'customer.profile.address_updated': 'Адрес успешно обновлён',
    'customer.profile.cannot_delete_only_address': 'Нельзя удалить единственный адрес',
    'customer.profile.address_deleted': 'Адрес успешно удалён',
    'customer.profile.default_address_updated': 'Адрес по умолчанию обновлён',
    'customer.profile.account_type_changed': 'Тип аккаунта изменён на ${type}',
    'customer.profile.retry_loading': 'Повторить загрузку',
    'customer.profile.change_picture': 'Изменить фото профиля',
    'customer.profile.orders': 'заказов',
    'customer.profile.account_type': 'Тип аккаунта',
    'customer.profile.tab.business': 'Бизнес',
    'customer.profile.first_name': 'Имя',
    'customer.profile.last_name': 'Фамилия',
    'customer.profile.email': 'Email',
    'customer.profile.phone': 'Номер телефона',
    'customer.profile.date_of_birth': 'Дата рождения',
    'customer.profile.select_business_type': 'Выберите тип бизнеса',
    'customer.profile.business_type_retail': 'Розничный магазин',
    'customer.profile.business_type_food': 'Ресторан/Общественное питание',
    'customer.profile.business_type_ecommerce': 'Электронная коммерция',
    'customer.profile.business_type_manufacturing': 'Производство',
    'customer.profile.business_type_healthcare': 'Здравоохранение',
    'customer.profile.business_type_education': 'Образование',
    'customer.profile.business_type_construction': 'Строительство',
    'customer.profile.business_type_professional': 'Профессиональные услуги',
    'customer.profile.business_type_other': 'Другое',
    'customer.profile.add_new_address': 'Добавить новый адрес',
    'customer.profile.label': 'Метка',
    'customer.profile.label_home': 'Дом',
    'customer.profile.label_office': 'Офис',
    'customer.profile.label_business': 'Бизнес',
    'customer.profile.label_other': 'Другое',
    'customer.profile.street_address': 'Улица и дом',
    'customer.profile.street_address_placeholder': 'ул. Главная, д. 123',
    'customer.profile.city': 'Город',
    'customer.profile.city_placeholder': 'Нью-Йорк',
    'customer.profile.state': 'Штат/Регион',
    'customer.profile.state_placeholder': 'NY',
    'customer.profile.zip_code': 'Почтовый индекс',
    'customer.profile.zip_code_placeholder': '10001',
    'customer.profile.set_as_default': 'Установить как адрес по умолчанию',
    'customer.profile.notes': 'Примечания',
    'customer.profile.optional': 'Необязательно',
    'customer.profile.notes_placeholder': 'Любые специальные инструкции для доставки',
    'customer.profile.no_addresses': 'Нет сохранённых адресов',
    'customer.profile.add_first_address': 'Добавить первый адрес',
    'customer.profile.default_badge': 'По умолчанию',
    'customer.profile.inactive_badge': 'Неактивно',
    'customer.profile.note': 'Примечание',
    'customer.profile.set_default_button': 'Сделать по умолчанию',
    'customer.profile.delete_address_title': 'Удалить адрес',
    'customer.profile.delete_address_description': 'Вы уверены, что хотите удалить этот адрес? Это действие нельзя отменить.',
    'customer.profile.payment_setup_info': 'Настройка способа оплаты откроется здесь',
    'customer.profile.payment_integration_info': 'Интеграция способов оплаты будет реализована отдельно',
    'customer.profile.payment_service_info': 'Это подключится к платежному сервису, такому как Stripe',
    'customer.profile.connect_payment_method': 'Подключить способ оплаты',
    'customer.profile.notification_preferences': 'Настройки уведомлений',
    'customer.profile.email_notifications': 'Email уведомления',
    'customer.profile.email_notifications_desc': 'Обновления заказов, чеки и рассылки',
    'customer.profile.email_preference_updated': 'Настройки email уведомлений обновлены',
    'customer.profile.sms_notifications': 'SMS уведомления',
    'customer.profile.sms_notifications_desc': 'Обновления доставки в реальном времени',
    'customer.profile.sms_preference_updated': 'Настройки SMS уведомлений обновлены',
    'customer.profile.push_notifications': 'Push-уведомления',
    'customer.profile.push_notifications_desc': 'Уведомления в приложении',
    'customer.profile.push_preference_updated': 'Настройки push-уведомлений обновлены',
    'customer.profile.privacy_preferences': 'Настройки конфиденциальности',
    'customer.profile.location_preference_updated': 'Настройки доступа к местоположению обновлены',
    'customer.profile.analytics_preference_updated': 'Настройки аналитики использования обновлены',
    'customer.profile.marketing_preference_updated': 'Настройки маркетинговых писем обновлены',
    'customer.profile.customer_service': 'Служба поддержки',
    'customer.profile.membership_level': 'Уровень членства',
    'customer.profile.account_status': 'Статус аккаунта',
    'customer.profile.active_since': 'Активен с ${date}',
    'customer.profile.address_management': 'Управление адресами',
    'customer.profile.saved_addresses_count': 'сохранённых адресов',
    'customer.profile.address_count': 'Адресов',
    'customer.profile.account_type_stat': 'Тип аккаунта',
    'customer.profile.business_account_full': 'Бизнес-аккаунт с полным функционалом',
    'customer.profile.personal_account_desc': 'Личный аккаунт',
    'customer.profile.business': 'Бизнес',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  // Update the t function in your LanguageContext.tsx
  const t = (key: string, variables?: Record<string, string>): string => {
    let translation = translations[language][key] || key;

    // Replace variables if provided
    if (variables) {
      Object.keys(variables).forEach(variable => {
        const placeholder = `\${${variable}}`;
        const value = variables[variable];
        translation = translation.replace(placeholder, value);
      });
    }

    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

// Add this function after the useLanguage hook
export function useCustomerTranslations() {
  const { t } = useLanguage();
  
  return {
    // Helper to easily access customer translations
    booking: {
      title: () => t('customer.booking.title'),
      subtitle: () => t('customer.booking.subtitle'),
      price_estimate: () => t('customer.booking.price_estimate'),
      pickup_address: () => t('customer.booking.pickup_address'),
      delivery_address: () => t('customer.booking.delivery_address'),
      item_category: () => t('customer.booking.item_category'),
      weight: () => t('customer.booking.weight'),
      volume: () => t('customer.booking.volume'),
      urgency: () => t('customer.booking.urgency'),
      special_requirements: () => t('customer.booking.special_requirements'),
      fragile: () => t('customer.booking.fragile'),
      refrigerated: () => t('customer.booking.refrigerated'),
      oversized: () => t('customer.booking.oversized'),
      hazardous: () => t('customer.booking.hazardous'),
      book_delivery: (amount: string) => t('customer.booking.book_delivery', { amount }),
      fill_all_fields: () => t('customer.booking.fill_all_fields'),
      calculating: () => t('customer.booking.calculating'),
    },
    
    bulk: {
      title: () => t('customer.bulk.title'),
      subtitle: () => t('customer.bulk.subtitle'),
      download_template: () => t('customer.bulk.download_template'),
      choose_file: () => t('customer.bulk.choose_file'),
      upload_success: (filename: string) => t('customer.bulk.upload_success', { filename }),
      processing: () => t('customer.bulk.processing'),
      review_orders: (count: string) => t('customer.bulk.review_orders', { count }),
      optimize_routes: () => t('customer.bulk.optimize_routes'),
      confirm_booking: () => t('customer.bulk.confirm_booking'),
      booking_confirmed: () => t('customer.bulk.booking_confirmed'),
      orders_placed: () => t('customer.bulk.orders_placed'),
      vehicles_assigned: () => t('customer.bulk.vehicles_assigned'),
      total_cost: () => t('customer.bulk.total_cost'),
      fuel_savings: () => t('customer.bulk.fuel_savings'),
    },
    
    tracking: {
      my_orders: () => t('customer.tracking.my_orders'),
      your_orders: () => t('customer.tracking.your_orders'),
      progress: () => t('customer.tracking.progress'),
      eta: (time: string) => t('customer.tracking.eta', { time }),
      driver_info: () => t('customer.tracking.driver_info'),
      pickup_address: () => t('customer.tracking.pickup_address'),
      delivery_address: () => t('customer.tracking.delivery_address'),
      order_timeline: () => t('customer.tracking.order_timeline'),
      mark_delivered: () => t('customer.tracking.mark_delivered'),
      rate_driver: () => t('customer.tracking.rate_driver'),
    },
    
    matching: {
      title: () => t('customer.matching.title'),
      subtitle: () => t('customer.matching.subtitle'),
      find_drivers: () => t('customer.matching.find_drivers'),
      location: () => t('customer.matching.location'),
      weight: () => t('customer.matching.weight'),
      volume: () => t('customer.matching.volume'),
      category: () => t('customer.matching.category'),
      radius: () => t('customer.matching.radius'),
      matched_drivers: (count: string) => t('customer.matching.matched_drivers', { count }),
      compatibility_score: (score: string) => t('customer.matching.compatibility_score', { score }),
    },
    
    notifications: {
      title: () => t('customer.notifications.title'),
      all: () => t('customer.notifications.all'),
      unread: () => t('customer.notifications.unread'),
      orders: () => t('customer.notifications.orders'),
      payments: () => t('customer.notifications.payments'),
      system: () => t('customer.notifications.system'),
      settings: () => t('customer.notifications.settings'),
      no_notifications: () => t('customer.notifications.no_notifications'),
      no_unread: () => t('customer.notifications.no_unread'),
      mark_all_read: () => t('customer.notifications.mark_all_read'),
    },
    
    profile: {
      tabs: {
        personal: () => t('customer.profile.tab.personal'),
        addresses: () => t('customer.profile.tab.addresses'),
        payment: () => t('customer.profile.tab.payment'),
        preferences: () => t('customer.profile.tab.preferences'),
        stats: () => t('customer.profile.tab.stats'),
      },
      no_profile: () => t('customer.profile.no_profile'),
      complete_onboarding: () => t('customer.profile.complete_onboarding'),
      go_to_onboarding: () => t('customer.profile.go_to_onboarding'),
    },
    
    dashboard: {
      title: () => t('customer.dashboard.title'),
      welcome: () => t('customer.dashboard.welcome'),
      active_orders: () => t('customer.dashboard.active_orders'),
      completed_orders: () => t('customer.dashboard.completed_orders'),
      total_spent: () => t('customer.dashboard.total_spent'),
      create_order: () => t('customer.dashboard.create_order'),
      view_all: () => t('customer.dashboard.view_all'),
      no_orders: () => t('customer.dashboard.no_orders'),
      get_started: () => t('customer.dashboard.get_started'),
    },
    
    common: {
      save: () => t('customer.common.save'),
      cancel: () => t('customer.common.cancel'),
      edit: () => t('customer.common.edit'),
      delete: () => t('customer.common.delete'),
      confirm: () => t('customer.common.confirm'),
      yes: () => t('customer.common.yes'),
      no: () => t('customer.common.no'),
      loading: () => t('customer.common.loading'),
      error: () => t('customer.common.error'),
      success: () => t('customer.common.success'),
      warning: () => t('customer.common.warning'),
      info: () => t('customer.common.info'),
    },
  };
}