import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Comprehensive translation dictionary
const translations = {
  en: {
    // Common
    'app.name': 'DeliveryMatch',
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.close': 'Close',
    'common.submit': 'Submit',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.back': 'Back',
    'common.continue': 'Continue',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.view': 'View',
    'common.upload': 'Upload',
    'common.download': 'Download',
    'common.print': 'Print',
    'common.share': 'Share',
    'common.copy': 'Copy',
    'common.paste': 'Paste',
    'common.cut': 'Cut',
    'common.undo': 'Undo',
    'common.redo': 'Redo',
    'common.select_all': 'Select All',
    'common.clear': 'Clear',
    'common.reset': 'Reset',
    'common.refresh': 'Refresh',
    'common.update': 'Update',
    'common.create': 'Create',
    'common.new': 'New',
    'common.open': 'Open',
    'common.start': 'Start',
    'common.stop': 'Stop',
    'common.pause': 'Pause',
    'common.resume': 'Resume',
    'common.finish': 'Finish',
    'common.complete': 'Complete',
    'common.pending': 'Pending',
    'common.approved': 'Approved',
    'common.rejected': 'Rejected',
    'common.expired': 'Expired',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.enabled': 'Enabled',
    'common.disabled': 'Disabled',
    'common.available': 'Available',
    'common.unavailable': 'Unavailable',
    'common.online': 'Online',
    'common.offline': 'Offline',
    'common.connected': 'Connected',
    'common.disconnected': 'Disconnected',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.warning': 'Warning',
    'common.info': 'Info',
    'common.help': 'Help',
    'common.support': 'Support',
    'common.contact': 'Contact',
    'common.about': 'About',
    'common.privacy': 'Privacy',
    'common.terms': 'Terms',
    'common.settings': 'Settings',
    'common.preferences': 'Preferences',
    'common.profile': 'Profile',
    'common.account': 'Account',
    'common.dashboard': 'Dashboard',
    'common.home': 'Home',
    'common.logout': 'Logout',
    'common.login': 'Login',
    'common.signup': 'Sign Up',
    'common.signin': 'Sign In',
    'common.email': 'Email',
    'common.password': 'Password',
    'common.username': 'Username',
    'common.name': 'Name',
    'common.first_name': 'First Name',
    'common.last_name': 'Last Name',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.city': 'City',
    'common.state': 'State',
    'common.country': 'Country',
    'common.zip_code': 'ZIP Code',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.today': 'Today',
    'common.yesterday': 'Yesterday',
    'common.tomorrow': 'Tomorrow',
    'common.week': 'Week',
    'common.month': 'Month',
    'common.year': 'Year',
    'common.hour': 'Hour',
    'common.minute': 'Minute',
    'common.second': 'Second',
    'common.price': 'Price',
    'common.cost': 'Cost',
    'common.total': 'Total',
    'common.subtotal': 'Subtotal',
    'common.tax': 'Tax',
    'common.discount': 'Discount',
    'common.fee': 'Fee',
    'common.amount': 'Amount',
    'common.quantity': 'Quantity',
    'common.weight': 'Weight',
    'common.size': 'Size',
    'common.dimension': 'Dimension',
    'common.length': 'Length',
    'common.width': 'Width',
    'common.height': 'Height',
    'common.volume': 'Volume',
    'common.description': 'Description',
    'common.note': 'Note',
    'common.comment': 'Comment',
    'common.message': 'Message',
    'common.notification': 'Notification',
    'common.alert': 'Alert',
    'common.reminder': 'Reminder',
    'common.language': 'Language',

    // Header
    'header.driver': 'Driver',
    'header.customer': 'Customer',

    // Landing Page
    'landing.title': 'Smart Delivery Platform',
    'landing.subtitle': 'Connect with verified drivers for efficient goods delivery. From single packages to bulk shipments, our AI-powered platform optimizes routes and reduces costs.',
    'landing.get_started': 'Get Started',
    'landing.ship_now': 'Ship Now',
    'landing.drive_earn': 'Drive & Earn',
    'landing.stats.drivers': 'Active Drivers',
    'landing.stats.deliveries': 'Deliveries Completed',
    'landing.stats.cities': 'Cities Covered',
    'landing.stats.rating': 'Average Rating',
    'landing.features.title': 'Why Choose DeliveryMatch?',
    'landing.features.subtitle': 'Built for efficiency, designed for scale. Our platform revolutionizes how goods move from point A to point B.',
    'landing.features.smart_matching.title': 'Smart Matching',
    'landing.features.smart_matching.desc': 'AI-powered algorithm matches orders with the most suitable drivers based on capacity, location, and route optimization.',
    'landing.features.bulk_orders.title': 'Bulk Orders',
    'landing.features.bulk_orders.desc': 'Upload multiple deliveries via Excel and get optimized route planning that saves time and fuel costs.',
    'landing.features.real_time_tracking.title': 'Real-time Tracking',
    'landing.features.real_time_tracking.desc': 'Track your deliveries in real-time with live GPS updates and instant notifications.',
    'landing.features.secure_reliable.title': 'Secure & Reliable',
    'landing.features.secure_reliable.desc': 'Verified drivers, secure payments, and comprehensive insurance coverage for peace of mind.',
    'landing.how_it_works.title': 'How It Works',
    'landing.how_it_works.subtitle': 'Simple steps to get your delivery moving',
    'landing.how_it_works.customers': 'For Customers',
    'landing.how_it_works.drivers': 'For Drivers',
    'landing.how_it_works.customer_step1': 'Create Request',
    'landing.how_it_works.customer_step1_desc': 'Enter pickup & delivery details',
    'landing.how_it_works.customer_step2': 'Get Matched',
    'landing.how_it_works.customer_step2_desc': 'AI finds the best driver for you',
    'landing.how_it_works.customer_step3': 'Track & Receive',
    'landing.how_it_works.customer_step3_desc': 'Real-time updates until delivery',
    'landing.how_it_works.driver_step1': 'Sign Up & Verify',
    'landing.how_it_works.driver_step1_desc': 'Upload documents & vehicle info',
    'landing.how_it_works.driver_step2': 'Get Orders',
    'landing.how_it_works.driver_step2_desc': 'Accept nearby delivery requests',
    'landing.how_it_works.driver_step3': 'Earn Money',
    'landing.how_it_works.driver_step3_desc': 'Complete deliveries & get paid',
    'landing.cta.title': 'Ready to Get Started?',
    'landing.cta.subtitle': 'Join thousands of customers and drivers who trust DeliveryMatch for their delivery needs.',
    'landing.cta.button': 'Start Your First Delivery',
    'landing.footer.subtitle': 'Connecting drivers and customers for efficient goods delivery.',

    // Auth Page
    'auth.title': 'DeliveryMatch',
    'auth.login.welcome': 'Welcome back!',
    'auth.signup.welcome': 'Create your account',
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.account_type': 'I want to:',
    'auth.customer_option': 'Ship goods and packages',
    'auth.driver_option': 'Drive and earn money',
    'auth.confirm_password': 'Confirm Password',
    'auth.agree_terms': 'I agree to the Terms of Service and Privacy Policy',
    'auth.forgot_password': 'Forgot your password?',
    'auth.no_account': "Don't have an account?",
    'auth.have_account': 'Already have an account?',
    'auth.demo_access': 'Quick Demo Access:',
    'auth.demo_customer': 'Demo Customer',
    'auth.demo_driver': 'Demo Driver',

    // Driver Dashboard
    'driver.dashboard.title': 'Driver Dashboard',
    'driver.dashboard.welcome': 'Welcome back, Driver!',
    'driver.dashboard.status': 'Status',
    'driver.dashboard.available': 'Available',
    'driver.dashboard.busy': 'Busy',
    'driver.dashboard.go_online': 'Go Online',
    'driver.dashboard.go_offline': 'Go Offline',
    'driver.dashboard.today_earnings': 'Today\'s Earnings',
    'driver.dashboard.active_orders': 'Active Orders',
    'driver.dashboard.completion_rate': 'Completion Rate',
    'driver.dashboard.rating': 'Your Rating',
    'driver.dashboard.available_orders': 'Available Orders',
    'driver.dashboard.no_orders': 'No available orders right now',
    'driver.dashboard.check_back': 'Check back in a few minutes for new delivery requests.',
    'driver.dashboard.accept_order': 'Accept Order',
    'driver.dashboard.pickup': 'Pickup',
    'driver.dashboard.delivery': 'Delivery',
    'driver.dashboard.earnings': 'Earnings',
    'driver.dashboard.distance': 'Distance',
    'driver.dashboard.quick_stats': 'Quick Stats',
    'driver.dashboard.this_week': 'This Week',
    'driver.dashboard.deliveries': 'Deliveries',
    'driver.dashboard.hours_online': 'Hours Online',

    // Navigation Tabs
    'nav.dashboard': 'Dashboard',
    'nav.orders': 'Active Orders',
    'nav.earnings': 'Earnings',
    'nav.notifications': 'Notifications',
    'nav.profile': 'Profile',
    'nav.booking': 'New Booking',
    'nav.bulk': 'Bulk Upload',
    'nav.tracking': 'Track Orders',
    'nav.matching': 'Find Drivers',

    // Notifications
    'notifications.title': 'Notifications',
    'notifications.unread': 'unread notifications',
    'notifications.all_caught_up': 'All caught up!',
    'notifications.mark_all_read': 'Mark All Read',
    'notifications.all': 'All',
    'notifications.unread_tab': 'Unread',
    'notifications.orders': 'Orders',
    'notifications.payments': 'Payments',
    'notifications.system': 'System',
    'notifications.settings': 'Settings',
    'notifications.preferences': 'Notification Preferences',
    'notifications.preferences_desc': 'Choose what notifications you want to receive',
    'notifications.types': 'Notification Types',
    'notifications.order_updates': 'Order Updates',
    'notifications.order_updates_desc': 'New orders, status changes, completions',
    'notifications.payment_notifications': 'Payment Notifications',
    'notifications.payment_notifications_desc': 'Payment confirmations, earnings updates',
    'notifications.system_updates': 'System Updates',
    'notifications.system_updates_desc': 'App updates, maintenance notifications',
    'notifications.promotions': 'Promotions & Tips',
    'notifications.promotions_desc': 'Special offers, driving tips, platform updates',
    'notifications.delivery_methods': 'Delivery Methods',
    'notifications.email_notifications': 'Email Notifications',
    'notifications.email_notifications_desc': 'Receive notifications via email',
    'notifications.sms_notifications': 'SMS Notifications',
    'notifications.sms_notifications_desc': 'Receive notifications via text message',
    'notifications.push_notifications': 'Push Notifications',
    'notifications.push_notifications_desc': 'Receive notifications in the app',
    'notifications.no_notifications': 'No notifications',
    'notifications.no_unread': 'All caught up! No unread notifications.',
    'notifications.no_category': 'No notifications in this category.',

    // Driver Profile
    'driver.profile.title': 'Driver Profile',
    'driver.profile.approved_drive': 'Approved to Drive',
    'driver.profile.cannot_drive': 'Cannot Drive',
    'driver.profile.completion': 'Profile Completion',
    'driver.profile.personal_info': 'Personal Information',
    'driver.profile.vehicle_info': 'Vehicle Information',
    'driver.profile.documents': 'Documents',
    'driver.profile.statistics': 'Statistics',
    'driver.profile.edit_profile': 'Edit Profile',
    'driver.profile.save_changes': 'Save Changes',
    'driver.profile.edit_vehicle': 'Edit Vehicle',
    'driver.profile.date_birth': 'Date of Birth',
    'driver.profile.member_since': 'Member Since',
    'driver.profile.vehicle_type': 'Vehicle Type',
    'driver.profile.license_plate': 'License Plate',
    'driver.profile.make': 'Make',
    'driver.profile.model': 'Model',
    'driver.profile.year': 'Year',
    'driver.profile.color': 'Color',
    'driver.profile.max_weight': 'Max Weight (kg)',
    'driver.profile.max_volume': 'Max Volume (m³)',
    'driver.profile.update_photo': 'Update Photo',
    'driver.profile.required_documents': 'Required Documents',
    'driver.profile.documents_desc': 'Keep your documents up to date to continue driving',
    'driver.profile.action_required': 'Action Required',
    'driver.profile.document_issues': 'You cannot accept orders until all document issues are resolved. Please upload or renew expired documents.',
    'driver.profile.driver_license': 'Driver License',
    'driver.profile.auto_insurance': 'Auto Insurance',
    'driver.profile.vehicle_registration': 'Vehicle Registration',
    'driver.profile.vehicle_inspection': 'Vehicle Inspection',
    'driver.profile.uploaded': 'Uploaded',
    'driver.profile.expires': 'Expires',
    'driver.profile.rejected': 'Rejected',
    'driver.profile.reupload': 'Re-upload',
    'driver.profile.upload_document': 'Upload Document',
    'driver.profile.upload_desc': 'Please upload a new {document} document. Make sure it\'s clear and not expired.',
    'driver.profile.stats.total_deliveries': 'Total Deliveries',
    'driver.profile.stats.average_rating': 'Average Rating',
    'driver.profile.stats.total_earnings': 'Total Earnings',
    'driver.profile.stats.completion_rate': 'Completion Rate',
    'driver.profile.verification': 'Verification Status',
    'driver.profile.background_check': 'Background Check',
    'driver.profile.driving_authorization': 'Driving Authorization',
    'driver.profile.authorized': 'Authorized',
    'driver.profile.suspended': 'Suspended',

    // Customer Profile
    'customer.profile.title': 'Customer Profile',
    'customer.profile.business_account': 'Business Account',
    'customer.profile.personal_account': 'Personal Account',
    'customer.profile.member_since': 'Member since',
    'customer.profile.personal': 'Personal',
    'customer.profile.addresses': 'Addresses',
    'customer.profile.payment': 'Payment',
    'customer.profile.preferences': 'Preferences',
    'customer.profile.statistics': 'Statistics',
    'customer.profile.personal_info': 'Personal Information',
    'customer.profile.business_info': 'Business Information',
    'customer.profile.business_name': 'Business Name',
    'customer.profile.business_type': 'Business Type',
    'customer.profile.business_address': 'Business Address',
    'customer.profile.business_phone': 'Business Phone',
    'customer.profile.tax_id': 'Tax ID',
    'customer.profile.saved_addresses': 'Saved Addresses',
    'customer.profile.add_address': 'Add Address',
    'customer.profile.default': 'Default',
    'customer.profile.set_default': 'Set Default',
    'customer.profile.delete_address': 'Delete Address',
    'customer.profile.delete_address_confirm': 'Are you sure you want to delete this address? This action cannot be undone.',
    'customer.profile.payment_methods': 'Payment Methods',
    'customer.profile.add_payment_method': 'Add Payment Method',
    'customer.profile.remove_payment_method': 'Remove Payment Method',
    'customer.profile.remove_payment_confirm': 'Are you sure you want to remove this payment method? This action cannot be undone.',
    'customer.profile.notification_prefs': 'Notification Preferences',
    'customer.profile.privacy_prefs': 'Privacy Preferences',
    'customer.profile.share_location': 'Share Location Data',
    'customer.profile.share_location_desc': 'Help improve route optimization',
    'customer.profile.share_analytics': 'Share Usage Analytics',
    'customer.profile.share_analytics_desc': 'Help improve the platform',
    'customer.profile.marketing_emails': 'Marketing Emails',
    'customer.profile.marketing_emails_desc': 'Promotional offers and tips',
    'customer.profile.account_stats': 'Account Statistics',
    'customer.profile.total_orders': 'Total Orders',
    'customer.profile.total_spent': 'Total Spent',
    'customer.profile.average_rating': 'Average Rating',
    'customer.profile.days_active': 'Days Active',
    'customer.profile.account_benefits': 'Account Benefits',
    'customer.profile.free_delivery': 'Free Delivery Credits',
    'customer.profile.loyalty_points': 'Loyalty Points',
    'customer.profile.bulk_discount': 'Bulk Discount Rate',

    // Earnings
    'earnings.title': 'Earnings & Payments',
    'earnings.subtitle': 'Manage your earnings and payment methods',
    'earnings.withdraw_funds': 'Withdraw Funds',
    'earnings.available_balance': 'Available Balance',
    'earnings.pending_payments': 'Pending Payments',
    'earnings.this_week': 'This Week',
    'earnings.total_earned': 'Total Earned',
    'earnings.overview': 'Overview',
    'earnings.transactions': 'Transaction History',
    'earnings.payment_methods': 'Payment Methods',
    'earnings.how_paid': 'How You Get Paid',
    'earnings.complete_delivery': 'Complete Delivery',
    'earnings.complete_delivery_desc': 'Customer confirms delivery and payment is processed',
    'earnings.payment_options': 'Payment Options',
    'earnings.cash_immediate': 'Cash: Keep immediately (report in app)',
    'earnings.card_digital': 'Card/Digital: Added to your balance',
    'earnings.automatic_payouts': 'Automatic Payouts',
    'earnings.daily_transfers': 'Daily automatic transfers to your bank',
    'earnings.weekly_transfers': 'Weekly automatic transfers to your bank',
    'earnings.instant_transfers': 'Instant transfers available',
    'earnings.next_payout': 'Next Payout',
    'earnings.recent_activity': 'Recent Activity',
    'earnings.withdraw_title': 'Withdraw Earnings',
    'earnings.payment_method': 'Payment Method',
    'earnings.select_payment_method': 'Select payment method',
    'earnings.minimum_withdrawal': 'Minimum withdrawal',
    'earnings.processing_time': 'Processing time: 1-3 business days',
    'earnings.no_fees': 'No withdrawal fees for bank transfers',
    'earnings.process_withdrawal': 'Process Withdrawal',
    'earnings.add_payment_method': 'Add Payment Method',
    'earnings.cash_payments': 'Cash Payments',
    'earnings.cash_instructions': 'Cash Payment Instructions',
    'earnings.cash_collect': 'Collect cash payment directly from customers',
    'earnings.cash_receipt': 'Always provide a receipt if requested',
    'earnings.cash_report': 'Report cash earnings in the app immediately after delivery',
    'earnings.cash_safe': 'Keep cash safe and deposit regularly',
    'earnings.cash_no_withdraw': 'Cash earnings are added to your total but don\'t require withdrawal',
    'earnings.add_payment_title': 'Add Payment Method',
    'earnings.add_payment_desc': 'Add a new way to receive your earnings',
    'earnings.payment_type': 'Payment Type',
    'earnings.bank_account': 'Bank Account',
    'earnings.digital_wallet': 'Digital Wallet (PayPal, etc.)',
    'earnings.account_name': 'Account Name',
    'earnings.account_details': 'Account Details',

    // Units and measurements
    'units.kg': 'kg',
    'units.m3': 'm³',
    'units.km': 'km',
    'units.minutes': 'minutes',
    'units.hours': 'hours',
    'units.days': 'days',

    // Status and states
    'status.pending': 'Pending',
    'status.approved': 'Approved',
    'status.rejected': 'Rejected',
    'status.expired': 'Expired',
    'status.completed': 'Completed',
    'status.processing': 'Processing',
    'status.failed': 'Failed',
    'status.active': 'Active',
    'status.inactive': 'Inactive'
  },
  
  ru: {
    // Common
    'app.name': 'ДоставкаМэтч',
    'common.loading': 'Загрузка...',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.add': 'Добавить',
    'common.remove': 'Удалить',
    'common.close': 'Закрыть',
    'common.submit': 'Отправить',
    'common.next': 'Далее',
    'common.previous': 'Назад',
    'common.back': 'Назад',
    'common.continue': 'Продолжить',
    'common.confirm': 'Подтвердить',
    'common.yes': 'Да',
    'common.no': 'Нет',
    'common.ok': 'ОК',
    'common.search': 'Поиск',
    'common.filter': 'Фильтр',
    'common.sort': 'Сортировка',
    'common.view': 'Просмотр',
    'common.upload': 'Загрузить',
    'common.download': 'Скачать',
    'common.print': 'Печать',
    'common.share': 'Поделиться',
    'common.copy': 'Копировать',
    'common.paste': 'Вставить',
    'common.cut': 'Вырезать',
    'common.undo': 'Отменить',
    'common.redo': 'Повторить',
    'common.select_all': 'Выбрать всё',
    'common.clear': 'Очистить',
    'common.reset': 'Сбросить',
    'common.refresh': 'Обновить',
    'common.update': 'Обновить',
    'common.create': 'Создать',
    'common.new': 'Новый',
    'common.open': 'Открыть',
    'common.start': 'Начать',
    'common.stop': 'Остановить',
    'common.pause': 'Пауза',
    'common.resume': 'Продолжить',
    'common.finish': 'Завершить',
    'common.complete': 'Завершить',
    'common.pending': 'Ожидание',
    'common.approved': 'Одобрено',
    'common.rejected': 'Отклонено',
    'common.expired': 'Истекло',
    'common.active': 'Активный',
    'common.inactive': 'Неактивный',
    'common.enabled': 'Включено',
    'common.disabled': 'Отключено',
    'common.available': 'Доступно',
    'common.unavailable': 'Недоступно',
    'common.online': 'Онлайн',
    'common.offline': 'Офлайн',
    'common.connected': 'Подключено',
    'common.disconnected': 'Отключено',
    'common.success': 'Успех',
    'common.error': 'Ошибка',
    'common.warning': 'Предупреждение',
    'common.info': 'Информация',
    'common.help': 'Помощь',
    'common.support': 'Поддержка',
    'common.contact': 'Контакты',
    'common.about': 'О нас',
    'common.privacy': 'Конфиденциальность',
    'common.terms': 'Условия',
    'common.settings': 'Настройки',
    'common.preferences': 'Предпочтения',
    'common.profile': 'Профиль',
    'common.account': 'Аккаунт',
    'common.dashboard': 'Панель управления',
    'common.home': 'Главная',
    'common.logout': 'Выйти',
    'common.login': 'Войти',
    'common.signup': 'Регистрация',
    'common.signin': 'Войти',
    'common.email': 'Email',
    'common.password': 'Пароль',
    'common.username': 'Имя пользователя',
    'common.name': 'Имя',
    'common.first_name': 'Имя',
    'common.last_name': 'Фамилия',
    'common.phone': 'Телефон',
    'common.address': 'Адрес',
    'common.city': 'Город',
    'common.state': 'Регион',
    'common.country': 'Страна',
    'common.zip_code': 'Почтовый индекс',
    'common.date': 'Дата',
    'common.time': 'Время',
    'common.today': 'Сегодня',
    'common.yesterday': 'Вчера',
    'common.tomorrow': 'Завтра',
    'common.week': 'Неделя',
    'common.month': 'Месяц',
    'common.year': 'Год',
    'common.hour': 'Час',
    'common.minute': 'Минута',
    'common.second': 'Секунда',
    'common.price': 'Цена',
    'common.cost': 'Стоимость',
    'common.total': 'Итого',
    'common.subtotal': 'Промежуточный итог',
    'common.tax': 'Налог',
    'common.discount': 'Скидка',
    'common.fee': 'Комиссия',
    'common.amount': 'Сумма',
    'common.quantity': 'Количество',
    'common.weight': 'Вес',
    'common.size': 'Размер',
    'common.dimension': 'Размер',
    'common.length': 'Длина',
    'common.width': 'Ширина',
    'common.height': 'Высота',
    'common.volume': 'Объём',
    'common.description': 'Описание',
    'common.note': 'Заметка',
    'common.comment': 'Комментарий',
    'common.message': 'Сообщение',
    'common.notification': 'Уведомление',
    'common.alert': 'Предупреждение',
    'common.reminder': 'Напоминание',
    'common.language': 'Язык',

    // Header
    'header.driver': 'Водитель',
    'header.customer': 'Клиент',

    // Landing Page
    'landing.title': 'Умная платформа доставки',
    'landing.subtitle': 'Связывайтесь с проверенными водителями для эффективной доставки товаров. От отдельных посылок до массовых отправлений, наша платформа с ИИ оптимизирует маршруты и снижает расходы.',
    'landing.get_started': 'Начать',
    'landing.ship_now': 'Отправить сейчас',
    'landing.drive_earn': 'Возить и зарабатывать',
    'landing.stats.drivers': 'Активных водителей',
    'landing.stats.deliveries': 'Доставок выполнено',
    'landing.stats.cities': 'Городов охвачено',
    'landing.stats.rating': 'Средний рейтинг',
    'landing.features.title': 'Почему стоит выбрать ДоставкаМэтч?',
    'landing.features.subtitle': 'Создано для эффективности, разработано для масштаба. Наша платформа революционизирует способ перемещения товаров из точки А в точку Б.',
    'landing.features.smart_matching.title': 'Умный подбор',
    'landing.features.smart_matching.desc': 'Алгоритм с ИИ подбирает заказы к наиболее подходящим водителям на основе грузоподъёмности, близости расположения и оптимизации маршрута.',
    'landing.features.bulk_orders.title': 'Массовые заказы',
    'landing.features.bulk_orders.desc': 'Загружайте несколько доставок через Excel и получайте оптимизированное планирование маршрутов, которое экономит время и топливо.',
    'landing.features.real_time_tracking.title': 'Отслеживание в реальном времени',
    'landing.features.real_time_tracking.desc': 'Отслеживайте свои доставки в реальном времени с живыми GPS-обновлениями и мгновенными уведомлениями.',
    'landing.features.secure_reliable.title': 'Безопасно и надёжно',
    'landing.features.secure_reliable.desc': 'Проверенные водители, безопасные платежи и комплексное страховое покрытие для спокойствия.',
    'landing.how_it_works.title': 'Как это работает',
    'landing.how_it_works.subtitle': 'Простые шаги для запуска вашей доставки',
    'landing.how_it_works.customers': 'Для клиентов',
    'landing.how_it_works.drivers': 'Для водителей',
    'landing.how_it_works.customer_step1': 'Создать запрос',
    'landing.how_it_works.customer_step1_desc': 'Введите детали забора и доставки',
    'landing.how_it_works.customer_step2': 'Найти подходящего',
    'landing.how_it_works.customer_step2_desc': 'ИИ находит лучшего водителя для вас',
    'landing.how_it_works.customer_step3': 'Отслеживать и получить',
    'landing.how_it_works.customer_step3_desc': 'Обновления в реальном времени до доставки',
    'landing.how_it_works.driver_step1': 'Зарегистрироваться и подтвердить',
    'landing.how_it_works.driver_step1_desc': 'Загрузите документы и информацию о транспорте',
    'landing.how_it_works.driver_step2': 'Получать заказы',
    'landing.how_it_works.driver_step2_desc': 'Принимайте близлежащие запросы на доставку',
    'landing.how_it_works.driver_step3': 'Зарабатывать деньги',
    'landing.how_it_works.driver_step3_desc': 'Выполняйте доставки и получайте оплату',
    'landing.cta.title': 'Готовы начать?',
    'landing.cta.subtitle': 'Присоединяйтесь к тысячам клиентов и водителей, которые доверяют ДоставкаМэтч для своих потребностей в доставке.',
    'landing.cta.button': 'Начать первую доставку',
    'landing.footer.subtitle': 'Соединяем водителей и клиентов для эффективной доставки товаров.',

    // Auth Page
    'auth.title': 'ДоставкаМэтч',
    'auth.login.welcome': 'Добро пожаловать!',
    'auth.signup.welcome': 'Создайте свой аккаунт',
    'auth.login': 'Войти',
    'auth.signup': 'Регистрация',
    'auth.account_type': 'Я хочу:',
    'auth.customer_option': 'Отправлять товары и посылки',
    'auth.driver_option': 'Возить и зарабатывать',
    'auth.confirm_password': 'Подтвердите пароль',
    'auth.agree_terms': 'Я согласен с Условиями обслуживания и Политикой конфиденциальности',
    'auth.forgot_password': 'Забыли пароль?',
    'auth.no_account': 'Нет аккаунта?',
    'auth.have_account': 'Уже есть аккаунт?',
    'auth.demo_access': 'Быстрый демо-доступ:',
    'auth.demo_customer': 'Демо клиент',
    'auth.demo_driver': 'Демо водитель',

    // Driver Dashboard
    'driver.dashboard.title': 'Панель водителя',
    'driver.dashboard.welcome': 'Добро пожаловать, водитель!',
    'driver.dashboard.status': 'Статус',
    'driver.dashboard.available': 'Доступен',
    'driver.dashboard.busy': 'Занят',
    'driver.dashboard.go_online': 'Выйти в сеть',
    'driver.dashboard.go_offline': 'Уйти в офлайн',
    'driver.dashboard.today_earnings': 'Заработок сегодня',
    'driver.dashboard.active_orders': 'Активные заказы',
    'driver.dashboard.completion_rate': 'Процент выполнения',
    'driver.dashboard.rating': 'Ваш рейтинг',
    'driver.dashboard.available_orders': 'Доступные заказы',
    'driver.dashboard.no_orders': 'Сейчас нет доступных заказов',
    'driver.dashboard.check_back': 'Проверьте снова через несколько минут для новых запросов на доставку.',
    'driver.dashboard.accept_order': 'Принять заказ',
    'driver.dashboard.pickup': 'Забрать',
    'driver.dashboard.delivery': 'Доставка',
    'driver.dashboard.earnings': 'Заработок',
    'driver.dashboard.distance': 'Расстояние',
    'driver.dashboard.quick_stats': 'Быстрая статистика',
    'driver.dashboard.this_week': 'На этой неделе',
    'driver.dashboard.deliveries': 'Доставки',
    'driver.dashboard.hours_online': 'Часов онлайн',

    // Navigation Tabs
    'nav.dashboard': 'Панель управления',
    'nav.orders': 'Активные заказы',
    'nav.earnings': 'Заработок',
    'nav.notifications': 'Уведомления',
    'nav.profile': 'Профиль',
    'nav.booking': 'Новый заказ',
    'nav.bulk': 'Массовая загрузка',
    'nav.tracking': 'Отслеживание заказов',
    'nav.matching': 'Поиск водителей',

    // Notifications
    'notifications.title': 'Уведомления',
    'notifications.unread': 'непрочитанных уведомлений',
    'notifications.all_caught_up': 'Все прочитано!',
    'notifications.mark_all_read': 'Отметить все как прочитанные',
    'notifications.all': 'Все',
    'notifications.unread_tab': 'Непрочитанные',
    'notifications.orders': 'Заказы',
    'notifications.payments': 'Платежи',
    'notifications.system': 'Система',
    'notifications.settings': 'Настройки',
    'notifications.preferences': 'Настройки уведомлений',
    'notifications.preferences_desc': 'Выберите, какие уведомления вы хотите получать',
    'notifications.types': 'Типы уведомлений',
    'notifications.order_updates': 'Обновления заказов',
    'notifications.order_updates_desc': 'Новые заказы, изменения статуса, завершения',
    'notifications.payment_notifications': 'Уведомления о платежах',
    'notifications.payment_notifications_desc': 'Подтверждения платежей, обновления заработка',
    'notifications.system_updates': 'Системные обновления',
    'notifications.system_updates_desc': 'Обновления приложения, уведомления о техническом обслуживании',
    'notifications.promotions': 'Акции и советы',
    'notifications.promotions_desc': 'Специальные предложения, советы по вождению, обновления платформы',
    'notifications.delivery_methods': 'Способы доставки',
    'notifications.email_notifications': 'Email уведомления',
    'notifications.email_notifications_desc': 'Получать уведомления по электронной почте',
    'notifications.sms_notifications': 'SMS уведомления',
    'notifications.sms_notifications_desc': 'Получать уведомления по SMS',
    'notifications.push_notifications': 'Push-уведомления',
    'notifications.push_notifications_desc': 'Получать уведомления в приложении',
    'notifications.no_notifications': 'Нет уведомлений',
    'notifications.no_unread': 'Все прочитано! Нет непрочитанных уведомлений.',
    'notifications.no_category': 'Нет уведомлений в этой категории.',

    // Driver Profile
    'driver.profile.title': 'Профиль водителя',
    'driver.profile.approved_drive': 'Разрешено к вождению',
    'driver.profile.cannot_drive': 'Нельзя водить',
    'driver.profile.completion': 'Заполненность профиля',
    'driver.profile.personal_info': 'Личная информация',
    'driver.profile.vehicle_info': 'Информация о транспорте',
    'driver.profile.documents': 'Документы',
    'driver.profile.statistics': 'Статистика',
    'driver.profile.edit_profile': 'Редактировать профиль',
    'driver.profile.save_changes': 'Сохранить изменения',
    'driver.profile.edit_vehicle': 'Редактировать транспорт',
    'driver.profile.date_birth': 'Дата рождения',
    'driver.profile.member_since': 'Участник с',
    'driver.profile.vehicle_type': 'Тип транспорта',
    'driver.profile.license_plate': 'Номерной знак',
    'driver.profile.make': 'Марка',
    'driver.profile.model': 'Модель',
    'driver.profile.year': 'Год',
    'driver.profile.color': 'Цвет',
    'driver.profile.max_weight': 'Макс. вес (кг)',
    'driver.profile.max_volume': 'Макс. объём (м³)',
    'driver.profile.update_photo': 'Обновить фото',
    'driver.profile.required_documents': 'Обязательные документы',
    'driver.profile.documents_desc': 'Поддерживайте документы в актуальном состоянии для продолжения работы',
    'driver.profile.action_required': 'Требуются действия',
    'driver.profile.document_issues': 'Вы не можете принимать заказы, пока не решите все проблемы с документами. Пожалуйста, загрузите или обновите просроченные документы.',
    'driver.profile.driver_license': 'Водительские права',
    'driver.profile.auto_insurance': 'Автострахование',
    'driver.profile.vehicle_registration': 'Регистрация транспорта',
    'driver.profile.vehicle_inspection': 'Техосмотр транспорта',
    'driver.profile.uploaded': 'Загружено',
    'driver.profile.expires': 'Истекает',
    'driver.profile.rejected': 'Отклонено',
    'driver.profile.reupload': 'Загрузить заново',
    'driver.profile.upload_document': 'Загрузить документ',
    'driver.profile.upload_desc': 'Пожалуйста, загрузите новый документ {document}. Убедитесь, что он чёткий и не просроченный.',
    'driver.profile.stats.total_deliveries': 'Всего доставок',
    'driver.profile.stats.average_rating': 'Средний рейтинг',
    'driver.profile.stats.total_earnings': 'Общий заработок',
    'driver.profile.stats.completion_rate': 'Процент выполнения',
    'driver.profile.verification': 'Статус верификации',
    'driver.profile.background_check': 'Проверка данных',
    'driver.profile.driving_authorization': 'Разрешение на вождение',
    'driver.profile.authorized': 'Разрешено',
    'driver.profile.suspended': 'Приостановлено',

    // Customer Profile
    'customer.profile.title': 'Профиль клиента',
    'customer.profile.business_account': 'Бизнес-аккаунт',
    'customer.profile.personal_account': 'Личный аккаунт',
    'customer.profile.member_since': 'Участник с',
    'customer.profile.personal': 'Личное',
    'customer.profile.addresses': 'Адреса',
    'customer.profile.payment': 'Платежи',
    'customer.profile.preferences': 'Предпочтения',
    'customer.profile.statistics': 'Статистика',
    'customer.profile.personal_info': 'Личная информация',
    'customer.profile.business_info': 'Информация о бизнесе',
    'customer.profile.business_name': 'Название компании',
    'customer.profile.business_type': 'Тип бизнеса',
    'customer.profile.business_address': 'Адрес компании',
    'customer.profile.business_phone': 'Телефон компании',
    'customer.profile.tax_id': 'Налоговый номер',
    'customer.profile.saved_addresses': 'Сохранённые адреса',
    'customer.profile.add_address': 'Добавить адрес',
    'customer.profile.default': 'По умолчанию',
    'customer.profile.set_default': 'Установить по умолчанию',
    'customer.profile.delete_address': 'Удалить адрес',
    'customer.profile.delete_address_confirm': 'Вы уверены, что хотите удалить этот адрес? Это действие нельзя отменить.',
    'customer.profile.payment_methods': 'Способы оплаты',
    'customer.profile.add_payment_method': 'Добавить способ оплаты',
    'customer.profile.remove_payment_method': 'Удалить способ оплаты',
    'customer.profile.remove_payment_confirm': 'Вы уверены, что хотите удалить этот способ оплаты? Это действие нельзя отменить.',
    'customer.profile.notification_prefs': 'Настройки уведомлений',
    'customer.profile.privacy_prefs': 'Настройки конфиденциальности',
    'customer.profile.share_location': 'Делиться данными о местоположении',
    'customer.profile.share_location_desc': 'Помочь улучшить оптимизацию маршрутов',
    'customer.profile.share_analytics': 'Делиться аналитикой использования',
    'customer.profile.share_analytics_desc': 'Помочь улучшить платформу',
    'customer.profile.marketing_emails': 'Маркетинговые письма',
    'customer.profile.marketing_emails_desc': 'Рекламные предложения и советы',
    'customer.profile.account_stats': 'Статистика аккаунта',
    'customer.profile.total_orders': 'Всего заказов',
    'customer.profile.total_spent': 'Всего потрачено',
    'customer.profile.average_rating': 'Средний рейтинг',
    'customer.profile.days_active': 'Дней активности',
    'customer.profile.account_benefits': 'Преимущества аккаунта',
    'customer.profile.free_delivery': 'Кредиты бесплатной доставки',
    'customer.profile.loyalty_points': 'Баллы лояльности',
    'customer.profile.bulk_discount': 'Скидка за объём',

    // Earnings
    'earnings.title': 'Заработок и платежи',
    'earnings.subtitle': 'Управляйте своими доходами и способами оплаты',
    'earnings.withdraw_funds': 'Вывести средства',
    'earnings.available_balance': 'Доступный баланс',
    'earnings.pending_payments': 'Ожидающие платежи',
    'earnings.this_week': 'На этой неделе',
    'earnings.total_earned': 'Всего заработано',
    'earnings.overview': 'Обзор',
    'earnings.transactions': 'История транзакций',
    'earnings.payment_methods': 'Способы оплаты',
    'earnings.how_paid': 'Как вы получаете оплату',
    'earnings.complete_delivery': 'Завершить доставку',
    'earnings.complete_delivery_desc': 'Клиент подтверждает доставку и обрабатывается платёж',
    'earnings.payment_options': 'Варианты оплаты',
    'earnings.cash_immediate': 'Наличные: Оставить себе сразу (сообщить в приложении)',
    'earnings.card_digital': 'Карта/Цифровой: Добавлено к вашему балансу',
    'earnings.automatic_payouts': 'Автоматические выплаты',
    'earnings.daily_transfers': 'Ежедневные автоматические переводы в ваш банк',
    'earnings.weekly_transfers': 'Еженедельные автоматические переводы в ваш банк',
    'earnings.instant_transfers': 'Мгновенные переводы доступны',
    'earnings.next_payout': 'Следующая выплата',
    'earnings.recent_activity': 'Недавняя активность',
    'earnings.withdraw_title': 'Вывести заработок',
    'earnings.payment_method': 'Способ оплаты',
    'earnings.select_payment_method': 'Выберите способ оплаты',
    'earnings.minimum_withdrawal': 'Минимальный вывод',
    'earnings.processing_time': 'Время обработки: 1-3 рабочих дня',
    'earnings.no_fees': 'Нет комиссии за банковские переводы',
    'earnings.process_withdrawal': 'Обработать вывод',
    'earnings.add_payment_method': 'Добавить способ оплаты',
    'earnings.cash_payments': 'Наличные платежи',
    'earnings.cash_instructions': 'Инструкции по наличным платежам',
    'earnings.cash_collect': 'Получайте наличную оплату напрямую от клиентов',
    'earnings.cash_receipt': 'Всегда предоставляйте чек по запросу',
    'earnings.cash_report': 'Сообщайте о наличном заработке в приложении сразу после доставки',
    'earnings.cash_safe': 'Держите наличные в безопасности и регулярно сдавайте в банк',
    'earnings.cash_no_withdraw': 'Наличный заработок добавляется к общему, но не требует вывода',
    'earnings.add_payment_title': 'Добавить способ оплаты',
    'earnings.add_payment_desc': 'Добавьте новый способ получения ваших доходов',
    'earnings.payment_type': 'Тип платежа',
    'earnings.bank_account': 'Банковский счёт',
    'earnings.digital_wallet': 'Цифровой кошелёк (PayPal и др.)',
    'earnings.account_name': 'Название счёта',
    'earnings.account_details': 'Реквизиты счёта',

    // Units and measurements
    'units.kg': 'кг',
    'units.m3': 'м³',
    'units.km': 'км',
    'units.minutes': 'минут',
    'units.hours': 'часов',
    'units.days': 'дней',

    // Status and states
    'status.pending': 'Ожидание',
    'status.approved': 'Одобрено',
    'status.rejected': 'Отклонено',
    'status.expired': 'Истекло',
    'status.completed': 'Завершено',
    'status.processing': 'Обработка',
    'status.failed': 'Неудача',
    'status.active': 'Активный',
    'status.inactive': 'Неактивный'
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}